// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/brace-style.js
/**
 * @author Yosuke Ota
 */
'use strict'

const RuleTester = require('eslint').RuleTester
const rule = require('../../../eslint-plugin-vue/dist/rules/brace-style').default

const tester = new RuleTester({
  languageOptions: {
    parser: require('vue-eslint-parser'),
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('brace-style', rule, {
  valid: [
    `<template lang="pug">
div(:attr=\`function foo() {
  return true;
}\`)
</template>`,
    {
      code: `<template lang="pug">div(:attr="function foo() { return true; }")</template>`,
      options: ['1tbs', { allowSingleLine: true }]
    },
    `<template lang="pug">div(:[(function(){return(1)})()]="a")</template>`
  ],
  invalid: [
    {
      code: `
        <template lang="pug">
div(:attr=\`function foo()
{
  return true;
}\`)
</template>`,
      output: `
        <template lang="pug">
div(:attr=\`function foo() {
  return true;
}\`)
</template>`,
      errors: [
        {
          message:
            'Opening curly brace does not appear on the same line as controlling statement.',
          line: 4
        }
      ]
    }
    //     {
    //       code: `
    //         <template lang="pug">
    // div(:attr=\`function foo() { return true; }\`)
    // </template>`,
    //       output: `
    //         <template lang="pug">
    // div(:attr=\`function foo() {
    //  return true;
    // }\`)
    // </template>`,
    //       errors: [
    //         {
    //           message: 'Statement inside of curly braces should be on next line.',
    //           line: 3
    //         },
    //         {
    //           message:
    //             'Closing curly brace should be on the same line as opening curly brace or on the line after the previous block.',
    //           line: 3
    //         }
    //       ]
    //     },
    //     {
    //       code: `<template lang="pug">
    // div(:[(function(){return(1)})()]="(function(){return(1)})()")
    // </template>`,
    //       output: `<template lang="pug">
    // div(:[(function(){return(1)})()]=\`(function(){
    // return(1)
    // })()\`)
    // </template>`,
    //       errors: [
    //         {
    //           message: 'Statement inside of curly braces should be on next line.'
    //         },
    //         {
    //           message:
    //             'Closing curly brace should be on the same line as opening curly brace or on the line after the previous block.'
    //         }
    //       ]
    //     }
  ]
})
