// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/camelcase.js
/**
 * @author Yosuke Ota
 */
'use strict'

const RuleTester = require('eslint').RuleTester
const rule = require('../../../eslint-plugin-vue/lib/rules/camelcase')

const tester = new RuleTester({
  languageOptions: {
    parser: require('vue-eslint-parser'),
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('camelcase', rule, {
  valid: [
    `<template lang="pug">div(:attr="{ myPref: 1 }")</template>`,
    {
      code: `
        <template lang="pug">
div(@click=\`(\$event) => {
  const { my_pref } = \$event
}\`)
</template>`,
      options: [{ ignoreDestructuring: true }]
    }
  ],
  invalid: [
    {
      code: `<template lang="pug">div(:attr="{ my_pref: 1 }")</template>`,
      errors: [
        {
          message: "Identifier 'my_pref' is not in camel case.",
          line: 1
        }
      ]
    },
    {
      code: `
        <template lang="pug">
div(@click="(\$event) => {  const { my_pref } = \$event}")
</template>`,
      errors: [
        {
          message: "Identifier 'my_pref' is not in camel case.",
          line: 3
        }
      ]
    },
    {
      code: `
        <template lang="pug">
div(@click="const { my_pref } = \$event")
</template>`,
      errors: [
        {
          message: "Identifier 'my_pref' is not in camel case.",
          line: 3
        }
      ]
    }
  ]
})
