// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/html-quotes.js
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
'use strict'

// ------------------------------------------------------------------------------
// Requirements
// ------------------------------------------------------------------------------

const RuleTester = require('eslint').RuleTester
const rule = require('../../../eslint-plugin-vue/dist/rules/html-quotes').default

// ------------------------------------------------------------------------------
// Tests
// ------------------------------------------------------------------------------

const tester = new RuleTester({
  languageOptions: {
    parser: require('vue-eslint-parser'),
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('html-quotes', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      options: ['double']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class="foo")</template>`,
      options: ['double']
    },
    {
      filename: 'test.vue',
      code: `<template lang='pug'>.foo</template>`,
      options: ['single']
    },
    {
      filename: 'test.vue',
      code: `<template lang='pug'>div(:class='foo')</template>`,
      options: ['single']
    },
    // avoidEscape
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(attr='foo\"bar')</template>`,
      options: ['double', { avoidEscape: true }]
    },
    {
      filename: 'test.vue',
      code: `<template lang='pug'>div(attr="foo\'bar")</template>`,
      options: ['single', { avoidEscape: true }]
    }

    // Invalid EOF
    // {
    //   code: `<template lang="pug">div(class="foo)</template>`,
    //   options: ['single']
    // },
    // {
    //   code: `<template lang="pug">div(class='foo)</template>`,
    //   options: ['double']
    // }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(class='foo')</template>`,
      output: `<template lang="pug">div(class="foo")</template>`,
      errors: ['Expected to be enclosed by double quotes.']
    },
    // {
    //   filename: 'test.vue',
    //   code: `<template lang="pug">div(:class=foo)</template>`,
    //   output: `<template lang="pug">div(:class="foo")</template>`,
    //   errors: ['Expected to be enclosed by double quotes.']
    // },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class='foo')</template>`,
      output: `<template lang="pug">div(:class="foo")</template>`,
      errors: ['Expected to be enclosed by double quotes.']
    },
    // {
    //   filename: 'test.vue',
    //   code: `<template lang="pug">.foo</template>`,
    //   output: `<template lang="pug">.foo</template>`,
    //   options: ['double'],
    //   errors: ['Expected to be enclosed by double quotes.']
    // },
    // {
    //   filename: 'test.vue',
    //   code: `<template lang="pug">.foo</template>`,
    //   output: `<template lang="pug">.foo</template>`,
    //   options: ['double'],
    //   errors: ['Expected to be enclosed by double quotes.']
    // },
    // {
    //   filename: 'test.vue',
    //   code: `<template lang="pug">div(:class=foo)</template>`,
    //   output: `<template lang="pug">div(:class="foo")</template>`,
    //   options: ['double'],
    //   errors: ['Expected to be enclosed by double quotes.']
    // },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class='foo')</template>`,
      output: `<template lang="pug">div(:class="foo")</template>`,
      options: ['double'],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang='pug'>div(:class="foo")</template>`,
      output: `<template lang='pug'>div(:class='foo')</template>`,
      options: ['single'],
      errors: ['Expected to be enclosed by single quotes.']
    },
    // avoidEscape
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(attr='foo')</template>`,
      output: `<template lang="pug">div(attr="foo")</template>`,
      options: ['double', { avoidEscape: true }],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang='pug'>div(attr="bar")</template>`,
      output: `<template lang='pug'>div(attr='bar')</template>`,
      options: ['single', { avoidEscape: true }],
      errors: ['Expected to be enclosed by single quotes.']
    }
  ]
})
