// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/keyword-spacing.js
/**
 * @author Yosuke Ota
 */
'use strict'

const RuleTester = require('eslint').RuleTester
const rule = require('../../../eslint-plugin-vue/dist/rules/keyword-spacing').default

const tester = new RuleTester({
  languageOptions: {
    parser: require('vue-eslint-parser'),
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('keyword-spacing', rule, {
  valid: [
    `<template lang="pug">
div(@event=\`
  if (foo) {
    //...
  } else if (bar) {
    //...
  } else {
    //...
  }
\`)
</template>`,
    {
      code: `<template lang="pug">
div(@event=\`
  if(foo) {
    //...
  }else if(bar) {
    //...
  }else{
    //...
  }
\`)
</template>`,
      options: [{ before: false, after: false }]
    },
    `<template lang="pug">div(:[(function(){return(1)})()]="val")</template>`
  ],
  invalid: [
    {
      code: `<template lang="pug">
div(@event=\`
  if(foo) {
    //...
  }else if(bar) {
    //...
  }else{
    //...
  }
\`)
</template>`,
      output: `<template lang="pug">
div(@event=\`
  if (foo) {
    //...
  } else if (bar) {
    //...
  } else {
    //...
  }
\`)
</template>`,
      errors: [
        {
          message: 'Expected space(s) after "if".',
          line: 3
        },
        {
          message: 'Expected space(s) before "else".',
          line: 5
        },
        {
          message: 'Expected space(s) after "if".',
          line: 5
        },
        {
          message: 'Expected space(s) before "else".',
          line: 7
        },
        {
          message: 'Expected space(s) after "else".',
          line: 7
        }
      ]
    },
    {
      code: `<template lang="pug">
div(@event=\`
  if (foo) {
    //...
  } else if (bar) {
    //...
  } else {
    //...
  }
\`)
</template>`,
      options: [{ before: false, after: false }],
      output: `<template lang="pug">
div(@event=\`
  if(foo) {
    //...
  }else if(bar) {
    //...
  }else{
    //...
  }
\`)
</template>`,
      errors: [
        {
          message: 'Unexpected space(s) after "if".',
          line: 3
        },
        {
          message: 'Unexpected space(s) before "else".',
          line: 5
        },
        {
          message: 'Unexpected space(s) after "if".',
          line: 5
        },
        {
          message: 'Unexpected space(s) before "else".',
          line: 7
        },
        {
          message: 'Unexpected space(s) after "else".',
          line: 7
        }
      ]
    },
    {
      code: `<template lang="pug">div(:[(function(){return(1)})()]="(function(){return(1)})()")</template>`,
      output: `<template lang="pug">div(:[(function(){return(1)})()]="(function(){return (1)})()")</template>`,
      errors: [
        {
          message: 'Expected space(s) after "return".',
          line: 1
        }
      ]
    }
  ]
})
