// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/1ce68fa9def2c7d6da7aa5020c731860d7027459/tests/lib/rules/valid-v-pre.js
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
'use strict'

// ------------------------------------------------------------------------------
// Requirements
// ------------------------------------------------------------------------------

const RuleTester = require('eslint').RuleTester
const rule = require('../../../eslint-plugin-vue/lib/rules/valid-v-pre')

// ------------------------------------------------------------------------------
// Tests
// ------------------------------------------------------------------------------

const tester = new RuleTester({
  languageOptions: {
    parser: require('vue-eslint-parser'),
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('valid-v-pre', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-pre:aaa)</template>`,
      errors: ["'v-pre' directives require no argument."]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-pre.aaa)</template>`,
      errors: ["'v-pre' directives require no modifier."]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-pre="aaa")</template>`,
      errors: ["'v-pre' directives require no attribute value."]
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">div(v-pre=".")</template>`,
      errors: ["'v-pre' directives require no attribute value."]
    },
    // comment value
    {
      filename: 'comment-value.vue',
      code: `<template lang="pug">div(v-pre="/**/")</template>`,
      errors: ["'v-pre' directives require no attribute value."]
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">div(v-pre="")</template>`,
      errors: ["'v-pre' directives require no attribute value."]
    }
  ]
})
