// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/eqeqeq.test.ts
/**
 * @author Toru Nagashima
 */
import semver from 'semver'
import { RuleTester, ESLint } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/eqeqeq'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('eqeqeq', rule, {
  valid: [
    `<template lang="pug">div(:attr="a === 1")</template>`,
    // CSS vars injection
    `
    <style>
    .text {
      color: v-bind(a === 1 ? 'red' : 'blue')
    }
    </style>`
  ],
  invalid: [
    {
      code: `<template lang="pug">div(:attr="a == 1")</template>`,
      errors: [
        {
          message: "Expected '===' and instead saw '=='.",
          suggestions: semver.gte(ESLint.version, '9.26.0')
            ? [
                {
                  desc: "Use '===' instead of '=='.",
                  output: `<template lang="pug">div(:attr="a === 1")</template>`
                }
              ]
            : [],
          line: 1,
          column: 35,
          endLine: 1,
          endColumn: 37
        }
      ]
    },
    // CSS vars injection
    {
      code: `
      <style>
      .text {
        color: v-bind(a == 1 ? 'red' : 'blue')
      }
      </style>`,
      errors: [
        {
          message: "Expected '===' and instead saw '=='.",
          suggestions: semver.gte(ESLint.version, '9.26.0')
            ? [
                {
                  desc: "Use '===' instead of '=='.",
                  output: `
      <style>
      .text {
        color: v-bind(a === 1 ? 'red' : 'blue')
      }
      </style>`
                }
              ]
            : [],
          line: 4,
          column: 25,
          endLine: 4,
          endColumn: 27
        }
      ]
    }
  ]
})
