// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/first-attribute-linebreak.js
/**
 * @fileoverview Enforce the location of first attribute
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/first-attribute-linebreak'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('first-attribute-linebreak', rule, {
  valid: [
    {
      code: `<template lang="pug">component</template>`
    },
    {
      code: `<template lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(
  name="John Doe"
)
component(name="John Doe"
)
</template>`
    },
    {
      code: `<template lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(name="John Doe",
          age="30",
          job="Vet"
)
component(
  name="John Doe"
)
component(name="John Doe"
)
</template>`,
      options: [{ singleline: 'ignore', multiline: 'ignore' }]
    },
    {
      code: `<template lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(name="John Doe",
          age="30",
          job="Vet"
)
component(name="John Doe"
)
</template>`,
      options: [{ singleline: 'beside', multiline: 'ignore' }]
    },
    {
      code: `<template lang="pug">
component(name="John Doe",
          age="30",
          job="Vet"
)
component(
name="John Doe"
)
component(name="John Doe"
)
</template>`,
      options: [{ singleline: 'ignore', multiline: 'beside' }]
    },
    {
      code: `<template 
        lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(name="John Doe",
          age="30",
          job="Vet"
)
component(
  name="John Doe"
)
</template>`,
      options: [{ singleline: 'below', multiline: 'ignore' }]
    },
    {
      code: `<template lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(
  name="John Doe"
)
component(name="John Doe"
)
</template>`,
      options: [{ singleline: 'ignore', multiline: 'below' }]
    }
  ],

  invalid: [
    {
      code: `<template lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(name="John Doe",
          age="30",
          job="Vet"
)
component(
  name="John Doe"
)
component(name="John Doe"
)
</template>`,
      output: `<template lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(
name="John Doe",
          age="30",
          job="Vet"
)
component(
  name="John Doe"
)
component(name="John Doe"
)
</template>`,
      errors: [
        {
          message: 'Expected a linebreak before this attribute.',
          line: 7,
          column: 11,
          endLine: 7,
          endColumn: 26
        }
      ]
    },
    {
      code: `<template lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(name="John Doe",
          age="30",
          job="Vet"
)
component(
  name="John Doe"
)
component(name="John Doe"
)
</template>`,
      output: `<template lang="pug">
component( name="John Doe",
  age="30",
  job="Vet"
)
component(name="John Doe",
          age="30",
          job="Vet"
)
component( name="John Doe"
)
component(name="John Doe"
)
</template>`,
      options: [{ singleline: 'beside', multiline: 'beside' }],
      errors: [
        {
          message: 'Expected no linebreak before this attribute.',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 18
        },
        {
          message: 'Expected no linebreak before this attribute.',
          line: 12,
          column: 3,
          endLine: 12,
          endColumn: 18
        }
      ]
    },
    {
      code: `<template
  lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(name="John Doe",
          age="30",
          job="Vet"
)
component(
  name="John Doe"
)
component(name="John Doe"
)
</template>`,
      output: `<template
  lang="pug">
component(
  name="John Doe",
  age="30",
  job="Vet"
)
component(
name="John Doe",
          age="30",
          job="Vet"
)
component(
  name="John Doe"
)
component(
name="John Doe"
)
</template>`,
      options: [{ singleline: 'below', multiline: 'below' }],
      errors: [
        {
          message: 'Expected a linebreak before this attribute.',
          line: 8,
          column: 11,
          endLine: 8,
          endColumn: 26
        },
        {
          message: 'Expected a linebreak before this attribute.',
          line: 15,
          column: 11,
          endLine: 15,
          endColumn: 26
        }
      ]
    }
  ]
})
