// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/func-call-spacing.js
/**
 * @author Yosuke Ota
 */
const { RuleTester, ESLint } = await import('../../../eslint-compat')
import semver from 'semver'
import rule from 'eslint-plugin-vue/dist/rules/func-call-spacing'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('func-call-spacing', rule, {
  valid: [
    `<template lang="pug">div(:foo="foo()")</template>`,
    {
      code: `<template lang="pug">div(:foo="foo ()")</template>`,
      options: ['always']
    },
    `<template lang="pug">div(:[foo()]="value")</template>`,
    {
      code: `<template lang="pug">div(:[foo()]="value")</template>`,
      options: ['always']
    },
    // CSS vars injection
    `
    <style>
    .text {
      color: v-bind('foo()')
    }
    </style>`
  ],
  invalid: [
    {
      code: `<template lang="pug">div(:foo="foo ()")</template>`,
      output: `<template lang="pug">div(:foo="foo()")</template>`,
      errors: [
        {
          message: semver.lt(ESLint.version, '7.0.0')
            ? 'Unexpected newline between function name and paren.'
            : 'Unexpected whitespace between function name and paren.',
          line: 1,
          column: 32
        }
      ]
    },
    {
      code: `<template lang="pug">div(:foo="foo()")</template>`,
      options: ['always'],
      output: `<template lang="pug">div(:foo="foo ()")</template>`,
      errors: [
        {
          message: 'Missing space between function name and paren.',
          line: 1,
          column: 32
        }
      ]
    },

    // CSS vars injection
    {
      code: `
      <style>
      .text {
        color: v-bind('foo ()')
      }
      </style>`,
      output: `
      <style>
      .text {
        color: v-bind('foo()')
      }
      </style>`,
      errors: [
        {
          message: semver.lt(ESLint.version, '7.0.0')
            ? 'Unexpected newline between function name and paren.'
            : 'Unexpected whitespace between function name and paren.',
          line: 4,
          column: 24
        }
      ]
    }
  ]
})
