// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/max-lines-per-block.test.ts
/**
 * @author lsdsjy
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/max-lines-per-block'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('max-lines-per-block', rule, {
  valid: [
    {
      code: `
      <script>
        console.log(1)
      </script>
      <template lang="pug">div</template>
      `,
      options: [{ template: 1 }]
    },
    {
      code: `
      <template lang="pug">div</template>`,
      options: [{ template: 1, skipBlankLines: true }]
    },
    {
      code: `
      <template lang="pug">div</template>`,
      options: [{ script: 1, style: 1 }]
    }
  ],
  invalid: [
    {
      code: `
      <template lang="pug">div</template>`,
      options: [{ template: 1 }],
      errors: [
        {
          message: 'Block has too many lines (2). Maximum allowed is 1.',
          line: 2,
          column: 7,
          endLine: 5,
          endColumn: 18
        }
      ]
    },
    {
      code: `
      <script>

        const a = 1
        console.log(a)
      </script>
      `,
      options: [{ script: 1, skipBlankLines: true }],
      errors: [
        {
          message: 'Block has too many lines (2). Maximum allowed is 1.',
          line: 2,
          column: 7,
          endLine: 6,
          endColumn: 16
        }
      ]
    }
  ]
})
