// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/multiline-ternary.test.ts
/**
 * @author dev1437
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/multiline-ternary'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('multiline-ternary', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(:class=\`{
  'test': someReallyLongCondition ?
    aVeryLongOutput :
    thisCantFitOnASingleLine
}\`)
</template>`
    },
    {
      // doesn't check ternary statements in <script> block
      filename: 'test.vue',
      code: `
      <script>
        let test = someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(:class=\`{
  'test': someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine
}\`)
</template>`,
      options: ['never']
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">.test</template>
      <style>
        .test {
            color: v-bind('someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine')
        }
      </style>`,
      options: ['never']
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div(:class=\`{
  'test': someReallyLongCondition ?
    aVeryLongOutput : thisCantFitOnASingleLine
}\`)
</template>`,
      output: `
        <template lang="pug">
div(:class=\`{
            'test': someReallyLongCondition ?
              aVeryLongOutput
: thisCantFitOnASingleLine
          }\`)
</template>`,
      options: ['always-multiline'],
      errors: [
        {
          message:
            'Expected newline between consequent and alternate of ternary expression.',
          line: 5,
          column: 5,
          endLine: 5,
          endColumn: 20
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div(:class=\`{
  'test': someReallyLongCondition ?
    aVeryLongOutput : thisCantFitOnASingleLine
}\`)
</template>`,
      output: `
        <template lang="pug">
div(:class=\`{
  'test': someReallyLongCondition ?aVeryLongOutput : thisCantFitOnASingleLine
}\`)
</template>`,
      options: ['never'],
      errors: [
        {
          message:
            'Unexpected newline between test and consequent of ternary expression.',
          line: 4,
          column: 11,
          endLine: 4,
          endColumn: 34
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div(:class=\`{
  'test': someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine
}\`)
</template>`,
      output: `
        <template lang="pug">
div(:class=\`{
            'test': someReallyLongCondition
? aVeryLongOutput
: thisCantFitOnASingleLine
          }\`)
</template>`,
      errors: [
        {
          message:
            'Expected newline between test and consequent of ternary expression.',
          line: 4,
          column: 11,
          endLine: 4,
          endColumn: 34
        },
        {
          message:
            'Expected newline between consequent and alternate of ternary expression.',
          line: 4,
          column: 37,
          endLine: 4,
          endColumn: 52
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div(:style=\`{
  'test': someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine
}\`)
</template>`,
      output: `
        <template lang="pug">
div(:style=\`{
            'test': someReallyLongCondition
? aVeryLongOutput
: thisCantFitOnASingleLine
          }\`)
</template>`,
      errors: [
        {
          message:
            'Expected newline between test and consequent of ternary expression.',
          line: 4,
          column: 11,
          endLine: 4,
          endColumn: 34
        },
        {
          message:
            'Expected newline between consequent and alternate of ternary expression.',
          line: 4,
          column: 37,
          endLine: 4,
          endColumn: 52
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">.test</template>
        <style>
          .test {
              color: v-bind('someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine')
          }
        </style>`,
      output: `
        <template lang="pug">.test</template>
        <style>
          .test {
              color: v-bind('someReallyLongCondition
? aVeryLongOutput
: thisCantFitOnASingleLine')
          }
        </style>`,
      errors: [
        {
          message:
            'Expected newline between test and consequent of ternary expression.',
          line: 5,
          column: 30,
          endLine: 5,
          endColumn: 53
        },
        {
          message:
            'Expected newline between consequent and alternate of ternary expression.',
          line: 5,
          column: 56,
          endLine: 5,
          endColumn: 71
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(:class=\`{
  'test': someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine
}\`)
</template>
      <script>
        let test = someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine
      </script>`,
      output: `
      <template lang="pug">
div(:class=\`{
          'test': someReallyLongCondition
? aVeryLongOutput
: thisCantFitOnASingleLine
        }\`)
</template>
      <script>
        let test = someReallyLongCondition ? aVeryLongOutput : thisCantFitOnASingleLine
      </script>`,
      errors: [
        {
          message:
            'Expected newline between test and consequent of ternary expression.',
          line: 4,
          column: 11,
          endLine: 4,
          endColumn: 34
        },
        {
          message:
            'Expected newline between consequent and alternate of ternary expression.',
          line: 4,
          column: 37,
          endLine: 4,
          endColumn: 52
        }
      ]
    }
  ]
})
