// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/mustache-interpolation-spacing.test.ts
/**
 * @fileoverview enforce unified spacing in mustache interpolations.
 * @author Armano
 */
import rule from 'eslint-plugin-vue/dist/rules/mustache-interpolation-spacing'
import { RuleTester } from '../../../eslint-compat'
import vueEslintParser from 'vue-eslint-parser'

const ruleTester = new RuleTester({
  languageOptions: { parser: vueEslintParser, ecmaVersion: 2015 }
})

ruleTester.run('mustache-interpolation-spacing', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template></template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">#</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:style="  ", :class="       foo      ", v-if="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{ text }}</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{ }}</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{ }}</template>`,
      options: ['always']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{}}</template>`,
      options: ['never']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{text}}</template>`,
      options: ['never']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{ text }}</template>`,
      options: ['always']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{         }}</template>`,
      options: ['always']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{         }}</template>`,
      options: ['never']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{   text   }}</template>`,
      options: ['always']
    }
  ],

  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{ text}}</template>`,
      output: `<template lang="pug">div {{ text }}</template>`,
      options: ['always'],
      errors: [
        {
          message: "Expected 1 space before '}}', but not found.",
          line: 1,
          column: 23,
          endLine: 1,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{text }}</template>`,
      output: `<template lang="pug">div {{ text }}</template>`,
      options: ['always'],
      errors: [
        {
          message: "Expected 1 space after '{{', but not found.",
          line: 1,
          column: 16,
          endLine: 1,
          endColumn: 18
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{ text}}</template>`,
      output: `<template lang="pug">div {{text}}</template>`,
      options: ['never'],
      errors: [
        {
          message: "Expected no space after '{{', but found.",
          line: 1,
          column: 16,
          endLine: 1,
          endColumn: 19
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{text }}</template>`,
      output: `<template lang="pug">div {{text}}</template>`,
      options: ['never'],
      errors: [
        {
          message: "Expected no space before '}}', but found.",
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{text}}</template>`,
      output: `<template lang="pug">div {{ text }}</template>`,
      options: ['always'],
      errors: [
        {
          message: "Expected 1 space after '{{', but not found.",
          line: 1,
          column: 16,
          endLine: 1,
          endColumn: 18
        },
        {
          message: "Expected 1 space before '}}', but not found.",
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 24
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{ text }}</template>`,
      output: `<template lang="pug">div {{text}}</template>`,
      options: ['never'],
      errors: [
        {
          message: "Expected no space after '{{', but found.",
          line: 1,
          column: 16,
          endLine: 1,
          endColumn: 19
        },
        {
          message: "Expected no space before '}}', but found.",
          line: 1,
          column: 23,
          endLine: 1,
          endColumn: 26
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div {{   text   }}</template>`,
      output: `<template lang="pug">div {{text}}</template>`,
      options: ['never'],
      errors: [
        {
          message: "Expected no space after '{{', but found.",
          line: 1,
          column: 16,
          endLine: 1,
          endColumn: 21
        },
        {
          message: "Expected no space before '}}', but found.",
          line: 1,
          column: 25,
          endLine: 1,
          endColumn: 30
        }
      ]
    }
  ]
})
