// SKIP AUTOGENERATION
/* eslint-disable no-irregular-whitespace */
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-bare-strings-in-template.test.ts
/**
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-bare-strings-in-template'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module'
  }
})

tester.run('no-bare-strings-in-template', rule, {
  valid: [
    `
    <template lang="pug">
h1 {{ $t(&apos;foo.bar&apos;) }}
h1 {{ foo }}
h1(v-t="'foo.bar'")
</template>`,
    `
    <template lang="pug">
h1(v-text="'Lorem ipsum' + foo")
h1(v-text="foo")
h1(v-text="1")
h1(v-text="true")
h1(v-text)
h1(v-text=)
</template>`,
    `
    <template lang="pug">
h1 #
div(title="#")
</template>`,
    `
    <template lang="pug">
div (
div )
div ,
div .
div &amp;
div +
div -
div =
div *
div /
div #
div %
div !
div ?
div :
div [
div ]
div {
div }
div(title="<")
div(title=">")
div •
div —
div
div |
div (
div )
div ,
div .
div &amp;
div &amp;
div +
div −
div =
div *
div *
div /
div #
div %
div !
div ?
div :
div [
div [
div ]
div ]
div {
div {
div }
div }
div &lt;
div &lt;
div &gt;
div &gt;
div •
div •
div —
div –
div 
div
div
div |
div |
div |
div ( ) , . &amp; + - = * / # % ! ? : [ ] { } • — | ( ) , . &amp; &amp; + − = * * / # % ! ? : [ [ ] ] { { } } &lt; &lt; &gt; &gt; • • — –   | | |
div(title=\`( ) , . & + - = * / # % ! ? : [ ] { } < > • —   | ( ) , . & & + − = * * / # % ! ? : [ [ ] ] { { } } < < > > • • — –   	 
 | | |\`)
</template>`,
    {
      // https://github.com/vuejs/eslint-plugin-vue/issues/2681
      code: `
      <template lang="pug">
h1 foo
h1 foo_bar
</template>`,
      options: [{ allowlist: ['foo', 'foo_bar'] }]
    },
    {
      code: `
      <template lang="pug">h1 @@</template>`,
      options: [{ allowlist: ['@@'] }]
    },
    // regex
    {
      code: `
      <template lang="pug">h1 123 321</template>`,
      options: [{ allowlist: [String.raw`/\d+/g`] }]
    },
    {
      code: `
      <template lang="pug">
h1 $foo
h1 $bar
</template>`,
      options: [{ allowlist: [String.raw`/$\w+/`] }]
    },
    {
      code: `
      <template lang="pug">h1 foo123foo</template>`,
      options: [{ allowlist: [String.raw`/\d+/`, 'foo'] }]
    }
  ],
  invalid: [
    {
      code: `
      <template lang="pug">
h1 Lorem ipsum
div(title="Lorem ipsum", aria-label="Lorem ipsum", aria-placeholder="Lorem ipsum", aria-roledescription="Lorem ipsum", aria-valuetext="Lorem ipsum")
img(alt="Lorem ipsum")
input(placeholder="Lorem ipsum")
h1(v-text="'Lorem ipsum'")
</template>`,
      errors: [
        {
          message: 'Unexpected non-translated string used.',
          line: 3,
          column: 4,
          endLine: 3,
          endColumn: 15
        },
        {
          message: 'Unexpected non-translated string used in `title`.',
          line: 4,
          column: 11,
          endLine: 4,
          endColumn: 24
        },
        {
          message: 'Unexpected non-translated string used in `aria-label`.',
          line: 4,
          column: 37,
          endLine: 4,
          endColumn: 50
        },
        {
          message:
            'Unexpected non-translated string used in `aria-placeholder`.',
          line: 4,
          column: 69,
          endLine: 4,
          endColumn: 82
        },
        {
          message:
            'Unexpected non-translated string used in `aria-roledescription`.',
          line: 4,
          column: 105,
          endLine: 4,
          endColumn: 118
        },
        {
          message: 'Unexpected non-translated string used in `aria-valuetext`.',
          line: 4,
          column: 135,
          endLine: 4,
          endColumn: 148
        },
        {
          message: 'Unexpected non-translated string used in `alt`.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 22
        },
        {
          message: 'Unexpected non-translated string used in `placeholder`.',
          line: 6,
          column: 19,
          endLine: 6,
          endColumn: 32
        },
        {
          message: 'Unexpected non-translated string used in `v-text`.',
          line: 7,
          column: 11,
          endLine: 7,
          endColumn: 26
        }
      ]
    },
    {
      code: `
      <template lang="pug">
h1 Lorem
h1 Lorem ipsum
h1 ipsum
</template>`,
      options: [{ allowlist: ['Lorem'] }],
      errors: [
        {
          messageId: 'unexpected',
          line: 4,
          column: 4,
          endLine: 4,
          endColumn: 15
        },
        {
          messageId: 'unexpected',
          line: 5,
          column: 4,
          endLine: 5,
          endColumn: 9
        }
      ]
    },
    {
      code: `
      <template lang="pug">
h1 foo
h1 foo_bar
</template>`,
      options: [{ allowlist: ['foo'] }],
      errors: [
        {
          messageId: 'unexpected',
          line: 4,
          column: 4,
          endLine: 4,
          endColumn: 11
        }
      ]
    },
    {
      code: `
      <template lang="pug">
h1(foo="Lorem ipsum")
h1(bar="Lorem ipsum")
h2(foo="Lorem ipsum")
h2(bar="Lorem ipsum")
div(foo="Lorem ipsum")
div(bar="Lorem ipsum")
</template>`,
      options: [{ attributes: { '/^h\\d$/': ['foo'], h1: ['bar'] } }],
      errors: [
        {
          message: 'Unexpected non-translated string used in `foo`.',
          line: 3,
          column: 8,
          endLine: 3,
          endColumn: 21
        },
        {
          message: 'Unexpected non-translated string used in `bar`.',
          line: 4,
          column: 8,
          endLine: 4,
          endColumn: 21
        },
        {
          message: 'Unexpected non-translated string used in `foo`.',
          line: 5,
          column: 8,
          endLine: 5,
          endColumn: 21
        }
      ]
    },
    {
      code: `
      <template lang="pug">
h1(v-foo="'Lorem ipsum'")
h1(v-bar="'Lorem ipsum'")
</template>`,
      options: [{ directives: ['v-foo'] }],
      errors: [
        {
          message: 'Unexpected non-translated string used in `v-foo`.',
          line: 3,
          column: 10,
          endLine: 3,
          endColumn: 25
        }
      ]
    },
    {
      code: `
      <template lang="pug">h1 123, foo is invalid, 321</template>`,
      options: [{ allowlist: [String.raw`/^\d+$/g`] }],
      errors: [
        {
          messageId: 'unexpected',
          line: 2,
          column: 31,
          endLine: 2,
          endColumn: 55
        }
      ]
    },
    {
      code: `
      <template lang="pug">h1 foo123bar</template>`,
      options: [{ allowlist: [String.raw`/\d+/`, 'foo'] }],
      errors: [
        {
          messageId: 'unexpected',
          line: 2,
          column: 31,
          endLine: 2,
          endColumn: 40
        }
      ]
    }
  ]
})
