// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-deprecated-v-bind-sync.test.ts
/**
 * @author Przemyslaw Falowski (@przemkow)
 * @fileoverview Disallow use of deprecated `.sync` modifier on `v-bind` directive (in Vue.js 3.0.0+)
 */
import rule from 'eslint-plugin-vue/dist/rules/no-deprecated-v-bind-sync'
import { RuleTester } from '../../../eslint-compat'
import vueEslintParser from 'vue-eslint-parser'

const ruleTester = new RuleTester({
  languageOptions: { parser: vueEslintParser, ecmaVersion: 2015 }
})

ruleTester.run('no-deprecated-v-bind-sync', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind:foo="'bar'")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo="'bar'")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind:[dynamicArg]="'bar'")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:[dynamicArg]="'bar'")</template>`
    }
  ],

  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind:foo.sync="'bar'")</template>`,
      output: `<template lang="pug">MyComponent(v-model:foo="'bar'")</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="'bar'")</template>`,
      output: `<template lang="pug">MyComponent(v-model:foo="'bar'")</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 39
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind:[dynamicArg].sync="'bar'")</template>`,
      output: `<template lang="pug">MyComponent(v-model:[dynamicArg]="'bar'")</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 54
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:[dynamicArg].sync="'bar'")</template>`,
      output: `<template lang="pug">MyComponent(v-model:[dynamicArg]="'bar'")</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 48
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind.sync="'bar'")</template>`,
      output: null,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 41
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync.unknown="foo")</template>`,
      output: null,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 47
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:[dynamicArg].sync.unknown="foo")</template>`,
      output: null,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 56
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="x.foo")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="x.foo")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 69
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x]")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[x]")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 70
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x - 1]")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[x - 1]")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 74
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[\`\${x}\`]")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[\`\${x}\`]")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 75
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[\`prefix_\${x}\`]")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[\`prefix_\${x}\`]")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 82
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x ? x : \'_\']")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[x ? x : \'_\']")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 80
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x || \'_\']")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[x || \'_\']")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 77
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x()]")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[x()]")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 72
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[/r/.match(x) ? 0 : 1]")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[/r/.match(x) ? 0 : 1]")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 89
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[typeof x]")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[typeof x]")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 77
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[tag\`\${x}\`]")
</template>`,
      output:
        `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(v-model:foo="foo[tag\`\${x}\`]")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifier on 'v-bind' directive is deprecated. Use 'v-model:propName' instead.",
          line: 1,
          column: 52,
          endLine: 1,
          endColumn: 78
        }
      ]
    }
  ]
})
