// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/no-deprecated-html-element-is.js
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import parserVue from 'vue-eslint-parser'
import rule from 'eslint-plugin-vue/dist/rules/no-deprecated-html-element-is'
import { RuleTester } from '../../../eslint-compat'

const tester = new RuleTester({
  languageOptions: {
    parser: parserVue,
    ecmaVersion: 2019,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-deprecated-html-element-is', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">component(is="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">Foo(is="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">component(:is="\'foo\'")</template>`
    },

    // is="vue:xxx"
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(is="vue:foo")</template>`
    }
  ],

  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(is="foo")</template>`,
      errors: [
        {
          line: 1,
          column: 26,
          messageId: 'unexpected',
          endLine: 1,
          endColumn: 34
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:is="foo")</template>`,
      errors: [
        {
          line: 1,
          column: 26,
          messageId: 'unexpected'
        }
      ]
    }
  ]
})
