// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-duplicate-attr-inheritance.test.ts
/**
 * @fileoverview Disable inheritAttrs when using v-bind=&#34;$attrs&#34;
 * @author Hiroki Osame
 */
import rule from 'eslint-plugin-vue/dist/rules/no-duplicate-attr-inheritance'
import { RuleTester } from '../../../eslint-compat'
import vueEslintParser from 'vue-eslint-parser'

const ruleTester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2018,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})
ruleTester.run('no-duplicate-attr-inheritance', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div
</template>
        <script>
        export default { inheritAttrs: true }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div
</template>
        <script>
        const data = {};
        export default {
          ...data,
          inheritAttrs: true
        }
        </script>`
    },
    // ignore multi root by default
    {
      filename: 'test.vue',
      code: `
      <script setup>
      defineOptions({ inheritAttrs: true })
      </script>
      <template lang="pug">
div(v-bind="$attrs")
div
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-if="condition1")
div(v-if="condition2", v-bind="$attrs")
div(v-else)
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-if="condition1")
div(v-else-if="condition2")
div(v-bind="$attrs")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-bind="$attrs")
div(v-if="condition1")
div(v-else)
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-if="condition1")
div(v-else-if="condition2")
div(v-if="condition3", v-bind="$attrs")
</template>`,
      options: [{ checkMultiRootNodes: false }]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div
</template>
        <script>
        const inheritAttrs = false;
        export default { inheritAttrs }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div(v-bind="$attrs")
</template>
        <script>
        export default { inheritAttrs: false }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div(v-bind="$attrs")
</template>
        <script>
        export default { inheritAttrs: 0 }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div(v-bind:foo="$attrs")
</template>
        <script>
        export default {  }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default { inheritAttrs: false }
      </script>
      <script setup>
      </script>
      <template lang="pug">div(v-bind="$attrs")</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      defineOptions({ inheritAttrs: false })
      </script>
      <template lang="pug">div(v-bind="$attrs")</template>
      `
    }
  ],

  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-bind="$attrs")
</template>`,
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 3,
          column: 15,
          endLine: 3,
          endColumn: 21
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div(v-bind="$attrs")
</template>
        <script>
        export default {
          inheritAttrs: true
        }
        </script>`,
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 4,
          column: 15,
          endLine: 4,
          endColumn: 21
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default { inheritAttrs: true }
      </script>
      <script setup>
      </script>
      <template lang="pug">div(v-bind="$attrs")</template>
      `,
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 7,
          column: 40,
          endLine: 7,
          endColumn: 46
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      defineOptions({ inheritAttrs: true })
      </script>
      <template lang="pug">div(v-bind="$attrs")</template>
      `,
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 5,
          column: 40,
          endLine: 5,
          endColumn: 46
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div(v-bind="$attrs")
div
</template>`,
      options: [{ checkMultiRootNodes: true }],
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 2,
          column: 13,
          endLine: 2,
          endColumn: 19
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-if="condition1", v-bind="$attrs")
div(v-else)
div(v-if="condition2")
</template>`,
      options: [{ checkMultiRootNodes: true }],
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 3,
          column: 32,
          endLine: 3,
          endColumn: 38
        }
      ]
    },
    // condition group as a single root node
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-if="condition1", v-bind="$attrs")
div(v-else-if="condition2")
div(v-else)
</template>`,
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 3,
          column: 32,
          endLine: 3,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-if="condition1", v-bind="$attrs")
div(v-else-if="condition2")
div(v-else-if="condition3")
div(v-else)
</template>`,
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 3,
          column: 32,
          endLine: 3,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-if="condition1", v-bind="$attrs")
div(v-else)
</template>`,
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 3,
          column: 32,
          endLine: 3,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(v-if="condition1", v-bind="$attrs")</template>`,
      errors: [
        {
          message: 'Set "inheritAttrs" to false.',
          line: 2,
          column: 59,
          endLine: 2,
          endColumn: 65
        }
      ]
    }
  ]
})
