// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/no-deprecated-inline-template.js
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import parserVue from 'vue-eslint-parser'
import rule from 'eslint-plugin-vue/dist/rules/no-deprecated-inline-template'
import { RuleTester } from '../../../eslint-compat'

const tester = new RuleTester({
  languageOptions: {
    parser: parserVue,
    ecmaVersion: 2019,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-deprecated-inline-template', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
my-component
  div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
my-component(:inline-template="foo")
  div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
my-component(Inline-Template="foo")
  div
</template>`
    }
  ],

  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
my-component(inline-template)
  div
</template>`,
      errors: [
        {
          line: 2,
          column: 14,
          messageId: 'unexpected',
          endLine: 2,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
my-component(inline-template="foo")
  div
</template>`,
      errors: [{ messageId: 'unexpected' }]
    }
  ]
})
