// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-deprecated-scope-attribute.test.ts
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-deprecated-scope-attribute'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: { parser: vueEslintParser, ecmaVersion: 2015 }
})

tester.run('no-deprecated-scope-attribute', rule, {
  valid: [
    `<template lang="pug">
LinkList
  a(v-slot:name)
</template>`,
    `<template lang="pug">
LinkList
  a(#name)
</template>`,
    `<template lang="pug">
LinkList
  a(v-slot="{a}")
</template>`,
    `<template lang="pug">
LinkList
  a(#default="{a}")
</template>`,
    `<template lang="pug">
LinkList
  a(slot="name")
</template>`,
    `<template lang="pug">
LinkList
  a(slot-scope="{a}")
</template>`,
    `<template lang="pug">
LinkList
  a
</template>`
  ],
  invalid: [
    {
      code: `
      <template lang="pug">
LinkList
  template(scope="{a}")
    a
</template>`,
      output: `
      <template lang="pug">
LinkList
  template(slot-scope="{a}")
    a
</template>`,
      errors: [
        {
          message: '`scope` attributes are deprecated.',
          line: 4,
          column: 21,
          endLine: 4,
          endColumn: 26
        }
      ]
    },
    {
      code: `
      <template lang="pug">
LinkList
  template(slot="name", scope="{a}")
    a
</template>`,
      output: `
      <template lang="pug">
LinkList
  template(slot="name", slot-scope="{a}")
    a
</template>`,
      errors: [
        {
          message: '`scope` attributes are deprecated.',
          line: 4,
          column: 33,
          endLine: 4,
          endColumn: 38
        }
      ]
    }
  ]
})
