// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-deprecated-functional-template.test.ts
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import rule from 'eslint-plugin-vue/dist/rules/no-deprecated-functional-template'
import { RuleTester } from '../../../eslint-compat'
import vueEslintParser from 'vue-eslint-parser'

const ruleTester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2019,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

ruleTester.run('no-deprecated-functional-template', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template></template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div</template>`
    },
    {
      filename: 'test.vue',
      code: '<template f><div /></template>'
    }
  ],

  invalid: [
    {
      filename: 'test.vue',
      code: '<template functional></template>',
      errors: [
        {
          messageId: 'unexpected',
          line: 1,
          column: 11,
          endLine: 1,
          endColumn: 21
        }
      ]
    },
    {
      filename: 'test.vue',
      code: '<template functional><div /></template>',
      errors: [
        {
          messageId: 'unexpected',
          line: 1,
          column: 11,
          endLine: 1,
          endColumn: 21
        }
      ]
    }
  ]
})
