// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/no-empty-pattern.js
/**
 * @author Yosuke Ota
 */
import parserVue from 'vue-eslint-parser'
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-empty-pattern'

const tester = new RuleTester({
  languageOptions: {
    parser: parserVue,
    ecmaVersion: 2018,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-empty-pattern', rule, {
  valid: [
    `<template lang="pug">
div(@attr=\`() => {
    var {a = {}} = foo;
    var {a = []} = foo;
  }\`)
</template>`,
    `<template lang="pug">div(@attr="function foo({a = {}}) {}")</template>`,
    `<template lang="pug">div(@attr="function foo({a = []}) {}")</template>`,
    `<template lang="pug">div(@attr="({a = {}}) => a")</template>`,
    `<template lang="pug">div(@attr="({a = []}) => a")</template>`,
    `<template lang="pug">div(slot-scope="{a = []}")</template>`
  ],
  invalid: [
    {
      code: `<template lang="pug">
div(@attr=\`() => {
    var {} = foo;
    var [] = foo;
    var {a: {}} = foo;
    var {a: []} = foo;
  }\`)
</template>`,
      errors: [
        {
          message: 'Unexpected empty object pattern.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 11
        },
        {
          message: 'Unexpected empty array pattern.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 11
        },
        {
          message: 'Unexpected empty object pattern.',
          line: 5,
          column: 13,
          endLine: 5,
          endColumn: 15
        },
        {
          message: 'Unexpected empty array pattern.',
          line: 6,
          column: 13,
          endLine: 6,
          endColumn: 15
        }
      ]
    },
    {
      code: `<template lang="pug">div(@attr="function foo({}) {}")</template>`,
      errors: [
        {
          message: 'Unexpected empty object pattern.',
          line: 1,
          column: 46,
          endLine: 1,
          endColumn: 48
        }
      ]
    },
    {
      code: `<template lang="pug">div(@attr="function foo([]) {}")</template>`,
      errors: [
        {
          message: 'Unexpected empty array pattern.',
          line: 1,
          column: 46,
          endLine: 1,
          endColumn: 48
        }
      ]
    },
    {
      code: `<template lang="pug">div(@attr="function foo({a: {}}) {}")</template>`,
      errors: [
        {
          message: 'Unexpected empty object pattern.',
          line: 1,
          column: 50,
          endLine: 1,
          endColumn: 52
        }
      ]
    },
    {
      code: `<template lang="pug">div(@attr="function foo({a: []}) {}")</template>`,
      errors: [
        {
          message: 'Unexpected empty array pattern.',
          line: 1,
          column: 50,
          endLine: 1,
          endColumn: 52
        }
      ]
    },
    {
      code: `<template lang="pug">div(@attr="({}) => foo()")</template>`,
      errors: [
        {
          message: 'Unexpected empty object pattern.',
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 36
        }
      ]
    },
    {
      code: `<template lang="pug">div(@attr="([]) => foo()")</template>`,
      errors: [
        {
          message: 'Unexpected empty array pattern.',
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 36
        }
      ]
    },
    {
      code: `<template lang="pug">div(@attr="({a: {}}) => a")</template>`,
      errors: [
        {
          message: 'Unexpected empty object pattern.',
          line: 1,
          column: 38,
          endLine: 1,
          endColumn: 40
        }
      ]
    },
    {
      code: `<template lang="pug">div(@attr="({a: []}) => a")</template>`,
      errors: [
        {
          message: 'Unexpected empty array pattern.',
          line: 1,
          column: 38,
          endLine: 1,
          endColumn: 40
        }
      ]
    },
    {
      code: `<template lang="pug">div(slot-scope="{}")</template>`,
      errors: [
        {
          message: 'Unexpected empty object pattern.',
          line: 1,
          column: 38,
          endLine: 1,
          endColumn: 40
        }
      ]
    },
    {
      code: `<template lang="pug">div(slot-scope="[]")</template>`,
      errors: [
        {
          message: 'Unexpected empty array pattern.',
          line: 1,
          column: 38,
          endLine: 1,
          endColumn: 40
        }
      ]
    },
    {
      code: `<template lang="pug">div(slot-scope="{a: {}}")</template>`,
      errors: [
        {
          message: 'Unexpected empty object pattern.',
          line: 1,
          column: 42,
          endLine: 1,
          endColumn: 44
        }
      ]
    },
    {
      code: `<template lang="pug">div(slot-scope="{a: []}")</template>`,
      errors: [
        {
          message: 'Unexpected empty array pattern.',
          line: 1,
          column: 42,
          endLine: 1,
          endColumn: 44
        }
      ]
    }
  ]
})
