// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/no-loss-of-precision.js
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
const { RuleTester, ESLint } = await import('../../../eslint-compat')
import semver from 'semver'
import rule from 'eslint-plugin-vue/dist/rules/no-loss-of-precision'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})
tester.run('no-loss-of-precision', rule, {
  valid: [
    ...(semver.gte(ESLint.version, '7.1.0')
      ? [
          {
            filename: 'test.vue',
            code: `
            <template lang="pug">
| {{12345}}
| {{123.45}}
</template>`
          },
          {
            filename: 'test.vue',
            code: `
            <template lang="pug">MyComponent(num="12345678901234567890")</template>`
          }
        ]
      : [])
  ],
  invalid: [
    ...(semver.gte(ESLint.version, '7.1.0')
      ? [
          {
            filename: 'test.vue',
            code: `
            <template lang="pug">
| {{12345678901234567890}}
| {{0.12345678901234567890}}
</template>`,
            errors: [
              {
                message: 'This number literal will lose precision at runtime.',
                line: 3
              },
              {
                message: 'This number literal will lose precision at runtime.',
                line: 4
              }
            ]
          },
          {
            filename: 'test.vue',
            code: `<template lang="pug">MyComponent(:num="12345678901234567890")</template>`,
            errors: [
              {
                message: 'This number literal will lose precision at runtime.',
                line: 1
              }
            ]
          }
        ]
      : [
          {
            filename: 'test.vue',
            code: `<template lang="pug">MyComponent(:num="12345678901234567890")</template>`,
            errors: [
              'Failed to extend ESLint core rule "no-loss-of-precision". You may be able to use this rule by upgrading the version of ESLint. If you cannot upgrade it, turn off this rule.'
            ]
          }
        ])
  ]
})
