// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-literals-in-template.test.ts
/**
 * @author rzzf
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-literals-in-template'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module'
  }
})

tester.run('no-literals-in-template', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:arr="myArray")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:obj="myObject")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:callback="myFunction")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind="myProps")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:foo="bar")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:[foo]="bar")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:[foo].camel="bar")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:foo)</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:foo.camel)</template>`
    },
    // Excluded attributes
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class="['active', errorClass]")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class="{ active: isActive }")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:class="[]")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:style="{ color: 'red' }")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:style="[baseStyles, overridingStyles]")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:style="[]")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:slot-class="[{ active: isActive }]")</template>`,
      options: [{ ignores: ['slot-class'] }]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind:slot-style="{ color: themeColor }")</template>`,
      options: [{ ignores: ['slot-style'] }]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:slot-class="[{ active: isActive }]")</template>`,
      options: [{ ignores: ['/^slot-(?:class|style)$/'] }]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="i in arr")
  MyComponent(:data="{ index: i }")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
Child
  template(#default="{ foo }")
    MyComponent(:data="{ val: foo }")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="i in arr")
  MyComponent(:data="[i]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
Child
  template(#default="{ foo }")
    MyComponent(:data="[foo]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="i in arr")
  MyComponent(:callback="() => someFunction(someArgs, i)")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
Child
  template(#default="{ foo }")
    ChildComponent(:callback="() => someFunction(someArgs, foo)")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="i in arr")
  MyComponent(:callback="function() { return someFunction(someArgs, i) }")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
Child
  template(#default="{ foo }")
    ChildComponent(:callback="function() { return someFunction(someArgs, foo) }")
</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:arr="[]")</template>`,
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 24
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:arr="[1,2,3]")</template>`,
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:obj="{}")</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 24
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:slot-class="[{ active: isActive }]")</template>`,
      options: [{ ignores: ['slot-style'] }],
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 1,
          column: 37,
          endLine: 1,
          endColumn: 59
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:wrapper-class="[{ active: isActive }]")</template>`,
      options: [{ ignores: ['/^slot-(?:class|style)$/'] }],
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 1,
          column: 40,
          endLine: 1,
          endColumn: 62
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:obj="{name:'Tom', age: 123}")</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 44
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:callback="() => someFunction(someArgs)")</template>`,
      errors: [
        {
          message: 'Unexpected arrow function literal in template.',
          line: 1,
          column: 27,
          endLine: 1,
          endColumn: 55
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:callback="function() { return 1 }")</template>`,
      errors: [
        {
          message: 'Unexpected function literal in template.',
          line: 1,
          column: 27,
          endLine: 1,
          endColumn: 50
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:arr="[...myArray]")</template>`,
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 34
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:obj="{...myObject}")</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 35
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind="{foo: 1}")</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 32
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:foo="{}")</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 1,
          column: 28,
          endLine: 1,
          endColumn: 30
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:foo="[]")</template>`,
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 1,
          column: 28,
          endLine: 1,
          endColumn: 30
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:foo="() => someFunction(someArgs)")</template>`,
      errors: [
        {
          message: 'Unexpected arrow function literal in template.',
          line: 1,
          column: 28,
          endLine: 1,
          endColumn: 56
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:foo="function() { return 1 }")</template>`,
      errors: [
        {
          message: 'Unexpected function literal in template.',
          line: 1,
          column: 28,
          endLine: 1,
          endColumn: 51
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:[key]="{}")</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 1,
          column: 30,
          endLine: 1,
          endColumn: 32
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:[key]="[]")</template>`,
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 1,
          column: 30,
          endLine: 1,
          endColumn: 32
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:[key]="() => someFunction(someArgs)")</template>`,
      errors: [
        {
          message: 'Unexpected arrow function literal in template.',
          line: 1,
          column: 30,
          endLine: 1,
          endColumn: 58
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-bind:[key]="function() { return 1 }")</template>`,
      errors: [
        {
          message: 'Unexpected function literal in template.',
          line: 1,
          column: 30,
          endLine: 1,
          endColumn: 53
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:[key].camel="{}")</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 1,
          column: 30,
          endLine: 1,
          endColumn: 32
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:[key].camel="[]")</template>`,
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 1,
          column: 30,
          endLine: 1,
          endColumn: 32
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:[key].camel="() => someFunction(someArgs)")</template>`,
      errors: [
        {
          message: 'Unexpected arrow function literal in template.',
          line: 1,
          column: 30,
          endLine: 1,
          endColumn: 58
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:[key].camel="function() { return 1 }")</template>`,
      errors: [
        {
          message: 'Unexpected function literal in template.',
          line: 1,
          column: 30,
          endLine: 1,
          endColumn: 53
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="i in arr")
  MyComponent(:data="{ val: globalVars }")
</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 4,
          column: 33,
          endLine: 4,
          endColumn: 52
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
Child
  template(#default="{ foo }")
    MyComponent(:data="{ val: globalVars }")
</template>`,
      errors: [
        {
          message: 'Unexpected object literal in template.',
          line: 5,
          column: 35,
          endLine: 5,
          endColumn: 54
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="i in arr")
  MyComponent(:data="[globalVars]")
</template>`,
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 4,
          column: 33,
          endLine: 4,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
Child
  template(#default="{ foo }")
    MyComponent(:data="[globalVars]")
</template>`,
      errors: [
        {
          message: 'Unexpected array literal in template.',
          line: 5,
          column: 35,
          endLine: 5,
          endColumn: 47
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="i in arr")
  MyComponent(:callback="() => someFunction(someArgs, globalVars)")
</template>`,
      errors: [
        {
          message: 'Unexpected arrow function literal in template.',
          line: 4,
          column: 37,
          endLine: 4,
          endColumn: 77
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
Child
  template(#default="{ foo }")
    MyComponent(:callback="() => someFunction(someArgs, globalVars)")
</template>`,
      errors: [
        {
          message: 'Unexpected arrow function literal in template.',
          line: 5,
          column: 39,
          endLine: 5,
          endColumn: 79
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="i in arr")
  MyComponent(:callback="function() { return someFunction(someArgs, globalVars) }")
</template>`,
      errors: [
        {
          message: 'Unexpected function literal in template.',
          line: 4,
          column: 37,
          endLine: 4,
          endColumn: 93
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
Child
  template(#default="{ foo }")
    ChildComponent(:callback="function() { return someFunction(someArgs, globalVars) }")
</template>`,
      errors: [
        {
          message: 'Unexpected function literal in template.',
          line: 5,
          column: 42,
          endLine: 5,
          endColumn: 98
        }
      ]
    }
  ]
})
