// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-multiple-objects-in-class.test.ts
/**
 * @author tyankatsu <https://github.com/tyankatsu0105>
 */
import rule from 'eslint-plugin-vue/dist/rules/no-multiple-objects-in-class'
import { RuleTester } from '../../../eslint-compat'
import vueEslintParser from 'vue-eslint-parser'

const ruleTester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    sourceType: 'module'
  }
})

ruleTester.run('no-multiple-objects-in-class', rule, {
  valid: [
    `<template lang="pug">div(:class="[{'foo': isFoo}]")</template>`,
    `<template lang="pug">div(:class="[{'foo': isFoo, 'bar': isBar}]")</template>`,
    `<template lang="pug">div(v-foo:class="[{'foo': isFoo}, {'bar': isBar}]")</template>`
  ],
  invalid: [
    {
      code: `<template lang="pug">div(v-bind:class="[{'foo': isFoo}, {'bar': isBar}]")</template>`,
      errors: [
        {
          message: 'Unexpected multiple objects. Merge objects.',
          line: 1,
          column: 26,
          endLine: 1,
          endColumn: 73
        }
      ]
    },
    {
      code: `<template lang="pug">div(:class="[{'foo': isFoo}, {'bar': isBar}]")</template>`,
      errors: [
        {
          message: 'Unexpected multiple objects. Merge objects.',
          line: 1,
          column: 26,
          endLine: 1,
          endColumn: 67
        }
      ]
    },

    // sparse array
    {
      code: `<template lang="pug">div(v-bind:class="[,{'foo': isFoo}, {'bar': isBar}]")</template>`,
      errors: [
        {
          message: 'Unexpected multiple objects. Merge objects.',
          line: 1,
          column: 26,
          endLine: 1,
          endColumn: 74
        }
      ]
    }
  ]
})
