// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-root-v-if.test.ts
/**
 * @author Perry Song
 * @copyright 2023 Perry Song. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-root-v-if'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-root-v-if', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div abc</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div abc
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
// comment
div abc
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
// comment
div(v-if="foo") abc
div(v-else) abc
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
// comment
div(v-if="foo") abc
div(v-else-if="bar") abc
div(v-else) abc
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
c1(v-if="1")
c2(v-else-if="1")
c3(v-else)
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div(v-if="foo")
div(v-else-if="bar")
</template>`
    },
    {
      filename: 'test.vue',
      code: '<template src="foo.html"></template>'
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  textarea
  | test
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
table
  custom-thead
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">| {{a b c}}</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
| aaaaaa
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
| aaaaaa
div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-for="x in list")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">slot</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">template</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div(v-if="mode === 'a'")
div(v-if="mode === 'b'")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
div(v-if="foo")
</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">custom-component(v-if="foo")</template>`,
      errors: [
        {
          message:
            '`v-if` should not be used on root element without `v-else`.',
          line: 1,
          column: 1,
          endLine: 1,
          endColumn: 61
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-if="foo")</template>`,
      errors: [
        {
          message:
            '`v-if` should not be used on root element without `v-else`.',
          line: 1,
          column: 1,
          endLine: 1,
          endColumn: 48
        }
      ]
    }
  ]
})
