// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-restricted-html-elements.test.ts
/**
 * @author Doug Wade
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-restricted-html-elements'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-restricted-html-elements', rule as RuleModule, {
  valid: [
    {
      filename: 'test.vue',
      code: '',
      options: ['button']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      options: ['button']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">button(type="button")</template>`,
      options: ['div']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
.foo
  Button(type="button")
</template>`,
      options: ['button']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
main
  article
</template>`,
      options: [{ element: ['div', 'span'] }]
    },
    // SVG
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg
  rect(width="100", height="100")
</template>`,
      options: ['circle']
    },
    // Math
    {
      filename: 'test.vue',
      code: `<template lang="pug">
math
  mn 2
</template>`,
      options: ['mi']
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Element is missing end tag.<template><div><button type="button"></button><div></template>`,
      options: ['button'],
      errors: [
        {
          message: 'Unexpected use of forbidden element button.',
          line: 1,
          column: 65,
          endLine: 1,
          endColumn: 87
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
.foo
  button(type="button")
</template>`,
      options: ['div'],
      errors: [
        {
          message: 'Unexpected use of forbidden element div.',
          line: 2,
          column: 1,
          endLine: 2,
          endColumn: 5
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">marquee foo</template>`,
      options: [{ element: 'marquee', message: 'Custom error' }],
      errors: [
        {
          message: 'Custom error',
          line: 1,
          column: 22,
          endLine: 1,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
a
RouterLink
</template>`,
      options: [
        {
          element: ['a', 'RouterLink'],
          message: 'Prefer the use of <NuxtLink> component'
        }
      ],
      errors: [
        {
          message: 'Prefer the use of <NuxtLink> component',
          line: 2,
          column: 1,
          endLine: 2,
          endColumn: 2
        },
        {
          message: 'Prefer the use of <NuxtLink> component',
          line: 3,
          column: 1,
          endLine: 3,
          endColumn: 11
        }
      ]
    },
    // SVG
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg
  circle(r="50")
</template>`,
      options: ['circle'],
      errors: [
        {
          message: 'Unexpected use of forbidden element circle.',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 17
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg
  rect(width="100", height="100")
  path(d="M10,10 L20,20")
</template>`,
      options: [
        { element: ['rect', 'path'], message: 'Use simplified shapes instead' }
      ],
      errors: [
        {
          message: 'Use simplified shapes instead',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 34
        },
        {
          message: 'Use simplified shapes instead',
          line: 4,
          column: 3,
          endLine: 4,
          endColumn: 26
        }
      ]
    },
    // Math
    {
      filename: 'test.vue',
      code: `<template lang="pug">
math
  mfrac
    mn 1
    mn 2
</template>`,
      options: ['mfrac'],
      errors: [
        {
          message: 'Unexpected use of forbidden element mfrac.',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 8
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
math
  mi x
  mo =
  mn 5
</template>`,
      options: [{ element: 'mo', message: 'Avoid using operators directly' }],
      errors: [
        {
          message: 'Avoid using operators directly',
          line: 4,
          column: 3,
          endLine: 4,
          endColumn: 5
        }
      ]
    }
  ]
})
