// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-textarea-mustache.test.ts
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-textarea-mustache'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-textarea-mustache', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  textarea(v-model="text")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  Textarea {{text}}
</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  textarea {{text}}
</template>`,
      errors: [
        {
          message: "Unexpected mustache. Use 'v-model' instead.",
          line: 3,
          column: 12,
          endLine: 4,
          endColumn: 0
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  textarea(v-model="text") {{text}}
</template>`,
      errors: [
        {
          message: "Unexpected mustache. Use 'v-model' instead.",
          line: 3,
          column: 28,
          endLine: 4,
          endColumn: 0
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  textarea {{text}}
    | and
    | {{text}}
</template>`,
      errors: [
        {
          message: "Unexpected mustache. Use 'v-model' instead.",
          line: 3,
          column: 12,
          endLine: 4,
          endColumn: 0
        },
        {
          message: "Unexpected mustache. Use 'v-model' instead.",
          line: 5,
          column: 7,
          endLine: 6,
          endColumn: 0
        }
      ]
    }
  ]
})
