// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-undef-components.test.ts
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-undef-components'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-undef-components', rule, {
  valid: [
    // <script setup>
    {
      filename: 'test.vue',
      code: `
      <script setup>
        import Foo from './Foo.vue'
      </script>

      <template lang="pug">
Foo
Teleport
template(v-if="foo")
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
        import FooPascalCase from './component.vue'
        import BarPascalCase from './component.vue'
        import BazPascalCase from './component.vue'
      </script>

      <template lang="pug">
FooPascalCase
bar-pascal-case
bazPascalCase
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import fooCamelCase from './component.vue'
      import barCamelCase from './component.vue'
      </script>

      <template lang="pug">
fooCamelCase
bar-camel-case
</template>
      `
    },
    // namespace
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import * as Form from './form-components'
      </script>

      <template lang="pug">
Form.Input
  Form.Label label
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import Bar from './Bar.vue'
      </script>

      <template lang="pug">Foo</template>
      `,
      options: [{ ignorePatterns: ['Foo'] }]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import Bar from './Bar.vue'
      </script>

      <template lang="pug">CustomComponent</template>
      `,
      options: [
        {
          ignorePatterns: [String.raw`custom(\-\w+)+`]
        }
      ]
    },
    // circular references
    {
      filename: 'test.vue',
      code: `
      <script setup>
      </script>

      <template lang="pug">test</template>
      `
    },
    {
      filename: 'FooBar.vue',
      code: `
      <script setup>
      </script>

      <template lang="pug">
FooBar
foo-bar
</template>
      `
    },
    {
      filename: 'FooBar.vue',
      code: `
      <script>
      export default {
        name: 'BarFoo'
      }
      </script>
      <script setup>
      </script>

      <template lang="pug">
FooBar
foo-bar
BarFoo
bar-foo
</template>
      `
    },

    // options API
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">div Lorem ipsum</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent</template>`,
      options: [
        {
          ignorePatterns: [String.raw`custom(\-\w+)+`]
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent Some text</template>`,
      options: [
        {
          ignorePatterns: [String.raw`custom(\-\w+)+`]
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">custom-component Some text</template>`,
      options: [
        {
          ignorePatterns: [String.raw`custom(\-\w+)+`]
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">custom-component Some text</template>`,
      options: [
        {
          ignorePatterns: [String.raw`Custom(\w+)+`]
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">custom_component Some text</template>`,
      options: [
        {
          ignorePatterns: [String.raw`Custom(\w+)+`]
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">customComponent Some text</template>`,
      options: [
        {
          ignorePatterns: [String.raw`Custom(\w+)+`]
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
customComponent
  warm-code Text
  InfoBtnPrimary(value="text")
</template>`,
      options: [
        {
          ignorePatterns: [
            String.raw`Custom(\w+)+`,
            String.raw`Warm(\w+)+`,
            String.raw`InfoBtn(\w+)+`
          ]
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent</template>
        <script>
        export default defineNuxtComponent({
          components: {
            CustomComponent
          }
        })
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent</template>
        <script>
        export default {
          components: {
            CustomComponent
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent Some text</template>
        <script>
        export default {
          components: {
            CustomComponent
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(:is="'CustomComponent'")</template>
        <script>
        export default {
          components: {
            CustomComponent
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(:is="'CustomComponent'") Some text</template>
        <script>
        export default {
          components: {
            CustomComponent
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(v-if="showComponent", :is="'CustomComponent'")</template>
        <script>
        export default {
          data: () => ({
            showComponent: true
          }),
          components: {
            CustomComponent
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(v-if="showComponent", :is="'CustomComponent'")</template>
        <script>
        export default {
          data: () => ({
            showComponent: false
          }),
          components: {
            CustomComponent
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(:is="'div'")</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(is="div")</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(is="span") Text</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">Component(is="div")</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">Component(is="span") Text</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(:is="name")</template>
        <script>
        export default {
          data: () => ({ name: 'div' })
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(:is="name")</template>
        <script>
        export default {
          data: () => ({ name: 'warm-button' }),
          components: { WarmButton }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
teleport
suspense
suspense
  div Text
Teleport
Suspense
Suspense
  div Text
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
transition
transition-group
keep-alive
transition
  div Text
TransitionGroup
KeepAlive
Transition
  div Text
Slot
slot
slot foo
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">Custom-Component</template>
        <script>
        export default {
          components: {
            'custom-component': InfoPrimaryWrapper
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(is)</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">Component(is)</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">div(v-is="'CustomComponent'")</template>
        <script>
        export default {
          components: {
            CustomComponent
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent</template>
        <script>
        export default {
          name: 'CustomComponent'
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">custom-component</template>
        <script>
        export default {
          name: 'CustomComponent'
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">custom-component</template>
        <script>
        export default {
          name: \`CustomComponent\`
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(:is="'CustomComponent'")</template>
        <script>
        export default {
          name: 'CustomComponent'
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(is="CustomComponent")</template>
        <script>
        export default {
          name: 'CustomComponent'
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(is="vue:CustomComponent")</template>
        <script>
        export default {
          name: 'CustomComponent'
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">div(v-is="'CustomComponent'")</template>
        <script>
        export default {
          name: 'CustomComponent'
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
CustomComponentWithNamedSlots
  template(#slotA)
    div Text
</template>
        <script>
        export default {
          components: {
            CustomComponentWithNamedSlots
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">TheModal</template>

      <script setup>
      import TheModal from 'foo'
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <script setup lang="ts">
        import Foo from './Foo.vue'
        import {HelloWorld1} from './components/HelloWorld'
      </script>

      <template lang="pug">
Foo
HelloWorld1
</template>
      `,
      languageOptions: {
        parser: vueEslintParser,
        ecmaVersion: 6,
        sourceType: 'module',
        parserOptions: {
          parser: require.resolve('@typescript-eslint/parser'),
          templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
        }
      }
    }
  ],
  invalid: [
    // <script setup>
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import Bar from './Bar.vue'
      </script>

      <template lang="pug">Foo</template>
      `,
      errors: [
        {
          message: "The '<Foo>' component has been used, but not defined.",
          line: 6,
          column: 28,
          endLine: 6,
          endColumn: 31
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import PascalCase from './component.vue'
      </script>

      <template lang="pug">pascal_case</template>
      `,
      errors: [
        {
          message:
            "The '<pascal_case>' component has been used, but not defined.",
          line: 6,
          column: 28,
          endLine: 6,
          endColumn: 39
        }
      ]
    },
    // upstream `<Foo.Input />` (nested component reference): pug parses
    // `Foo.Input` as `<Foo class="Input">` — dotted component refs have
    // no pug analog, so this case is not portable.
    {
      filename: 'test.vue',
      code: `
      <script setup lang="ts">
        import type Foo from './Foo.vue'
        import type {HelloWorld1} from './components/HelloWorld'
        import { type HelloWorld2 } from './components/HelloWorld2'
        import type {HelloWorld as HelloWorld3} from './components/HelloWorld3'
        import { type HelloWorld as HelloWorld4 } from './components/HelloWorld4';
        import { type default as HelloWorld5 } from './components/HelloWorld5';
      </script>

      <template lang="pug">
Foo
HelloWorld1
HelloWorld2
HelloWorld3
HelloWorld4
HelloWorld5
</template>
      `,
      languageOptions: {
        parser: vueEslintParser,
        ecmaVersion: 6,
        sourceType: 'module',
        parserOptions: {
          parser: require.resolve('@typescript-eslint/parser'),
          templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
        }
      },
      errors: [
        {
          message:
            "The '<Foo>' component has been used, but 'Foo' only refers to a type.",
          line: 12,
          column: 1,
          endLine: 12,
          endColumn: 4
        },
        {
          message:
            "The '<HelloWorld1>' component has been used, but 'HelloWorld1' only refers to a type.",
          line: 13,
          column: 1,
          endLine: 13,
          endColumn: 12
        },
        {
          message:
            "The '<HelloWorld2>' component has been used, but 'HelloWorld2' only refers to a type.",
          line: 14,
          column: 1,
          endLine: 14,
          endColumn: 12
        },
        {
          message:
            "The '<HelloWorld3>' component has been used, but 'HelloWorld3' only refers to a type.",
          line: 15,
          column: 1,
          endLine: 15,
          endColumn: 12
        },
        {
          message:
            "The '<HelloWorld4>' component has been used, but 'HelloWorld4' only refers to a type.",
          line: 16,
          column: 1,
          endLine: 16,
          endColumn: 12
        },
        {
          message:
            "The '<HelloWorld5>' component has been used, but 'HelloWorld5' only refers to a type.",
          line: 17,
          column: 1,
          endLine: 17,
          endColumn: 12
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup lang="ts">
        type Foo = {}
      </script>

      <template lang="pug">Foo</template>
      `,
      languageOptions: {
        parser: vueEslintParser,
        ecmaVersion: 6,
        sourceType: 'module',
        parserOptions: {
          parser: require.resolve('@typescript-eslint/parser'),
          templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
        }
      },
      errors: [
        {
          message:
            "The '<Foo>' component has been used, but 'Foo' only refers to a type.",
          line: 6,
          column: 28,
          endLine: 6,
          endColumn: 31
        }
      ]
    },

    // options API
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent</template>`,
      errors: [
        {
          message:
            "The '<CustomComponent>' component has been used, but not defined.",
          line: 2,
          column: 30,
          endLine: 2,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">WarmButton</template>`,
      options: [
        {
          ignorePatterns: [String.raw`custom(\-\w+)+`]
        }
      ],
      errors: [
        {
          message:
            "The '<WarmButton>' component has been used, but not defined.",
          line: 2,
          column: 30,
          endLine: 2,
          endColumn: 40
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent Some text</template>`,
      errors: [
        {
          message:
            "The '<CustomComponent>' component has been used, but not defined.",
          line: 2,
          column: 30,
          endLine: 2,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">WarmButton Some text</template>`,
      options: [
        {
          ignorePatterns: [String.raw`custom(\-\w+)+`]
        }
      ],
      errors: [
        {
          message:
            "The '<WarmButton>' component has been used, but not defined.",
          line: 2,
          column: 30,
          endLine: 2,
          endColumn: 40
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent</template>
        <script>
        export default {
          components: {
            WarmButton
          }
        }
        </script>`,
      errors: [
        {
          message:
            "The '<CustomComponent>' component has been used, but not defined.",
          line: 2,
          column: 30,
          endLine: 2,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent Some text</template>
        <script>
        export default {
          components: {
            WarmButton
          }
        }
        </script>`,
      errors: [
        {
          message:
            "The '<CustomComponent>' component has been used, but not defined.",
          line: 2,
          column: 30,
          endLine: 2,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(:is="'CustomComponent'")</template>
        <script>
        export default {
          components: {
            WarmButton
          }
        }
        </script>`,
      errors: [
        {
          message:
            "The '<CustomComponent>' component has been used, but not defined.",
          line: 2,
          column: 40,
          endLine: 2,
          endColumn: 63
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">component(:is="'CustomComponent'") Some text</template>
        <script>
        export default {
          components: {
            WarmButton
          }
        }
        </script>`,
      errors: [
        {
          message:
            "The '<CustomComponent>' component has been used, but not defined.",
          line: 2,
          column: 40,
          endLine: 2,
          endColumn: 63
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent</template>
        <script>
        export default {
          components: {
            'custom-component': InfoPrimaryWrapper
          }
        }
        </script>`,
      errors: [
        {
          message:
            "The '<CustomComponent>' component has been used, but not defined.",
          line: 2,
          column: 30,
          endLine: 2,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">CustomComponent</template>
        <script>
        export default {
          name: CustomComponent
        }
        </script>`,
      errors: [
        {
          message:
            "The '<CustomComponent>' component has been used, but not defined.",
          line: 2,
          column: 30,
          endLine: 2,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
CustomComponentWithNamedSlots
  template(#slotA)
    div Text
</template>`,
      errors: [
        {
          message:
            "The '<CustomComponentWithNamedSlots>' component has been used, but not defined.",
          line: 3,
          column: 1,
          endLine: 3,
          endColumn: 30
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">div(is="vue:foo")</template>
        <script>
        export default {
          components: {
            bar
          }
        }
        </script>`,
      errors: [
        {
          message: "The '<foo>' component has been used, but not defined.",
          line: 2,
          column: 34,
          endLine: 2,
          endColumn: 46
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">div(v-is="'foo'")</template>
        <script>
        export default {
          components: {
            bar
          }
        }
        </script>`,
      errors: [
        {
          message: "The '<foo>' component has been used, but not defined.",
          line: 2,
          column: 34,
          endLine: 2,
          endColumn: 46
        }
      ]
    }
  ]
})
