// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-useless-template-attributes.test.ts
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-useless-template-attributes'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-useless-template-attributes', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
template(v-if="foo") ...
template(v-else-if="bar") ...
template(v-else) ...
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">template(v-for="e in list") ...</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">template(v-slot) ...</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
CoolButton
  template(slot="foo") ...
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
CoolButton
  template(slot-scope="foo") ...
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
CoolButton
  template(scope="foo") ...
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
// ignore
template(foo="a") ...
template(:foo="a") ...
template(v-unknown="a") ...
</template>`
    },
    // not template
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
.heading(v-if="foo") ...
div(v-for="i in foo", :bar="i") ...
div(v-slot:foo="foo", ref="input") ...
div(v-if="foo", @click="click") ...
</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
// ✓ GOOD
template(v-if="foo") ...
template(v-if="foo") ...
template(v-else-if="foo") ...
template(v-else) ...
template(v-for="i in foo", :key="i") ...
template(v-slot:foo) ...
// for Vue<=2.5
template(slot="foo") ...
template(:slot="foo") ...
template(slot-scope="param") ...
// for Vue<=2.4
template(scope="param") ...
// ✗ BAD
template.heading(v-if="foo") ...
template(v-for="i in foo", :bar="i") ...
template(v-slot:foo="foo", ref="input") ...
template(v-if="foo", @click="click") ...
// Ignore
template.heading ...
template(:bar="i") ...
template(ref="input") ...
template(@click="click") ...
</template>`,
      errors: [
        {
          message: 'Unexpected useless directive on `<template>`.',
          line: 18,
          column: 28,
          endLine: 18,
          endColumn: 36
        },
        {
          message: 'Unexpected useless attribute on `<template>`.',
          line: 19,
          column: 28,
          endLine: 19,
          endColumn: 39
        },
        {
          message: 'Unexpected useless directive on `<template>`.',
          line: 20,
          column: 22,
          endLine: 20,
          endColumn: 36
        }
      ]
    }
  ]
})
