// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-undef-directives.test.ts
/**
 * @author rzzf
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-undef-directives'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-undef-directives', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-text="text")
div(v-html="html")
div(v-show="true")
div(v-if="true")
div(v-else-if="true")
div(v-else)
div(v-for="item in items")
div(v-bind:id="id")
div(:id="id")
div(v-on:click="click")
div(@click="click")
div(v-model="value")
div
div(v-cloak)
div(v-once)
div(v-memo="[value]")
slot(v-bind="item")
component(v-bind:is="'div'")
template(v-slot:default)
template(#default)
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vFocus from './vFocus'
      const vFoo = {}
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus>
        <div v-foo></div>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vFocus from './vFocus'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-Focus>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vFocus from './vFocus'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus.foo>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vFocus from './vFocus'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus:foo>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vFocus from './vFocus'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus:foo.bar>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vFocus from './vFocus'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus:[arg]>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import {focus as vFocus} from './vFocus'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus.foo>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vClickOutside from './vClickOutside'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-click-outside>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vClickOutside from './vClickOutside'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-clickOutside>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default {
        directives: {
          focus: {},
        }
      }
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default {
        directives: {
          fooBar: {}
        }
      }
      </script>
      <template lang="pug">div(v-foo-bar)</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default {
        directives: {
          fooBar: {}
        }
      }
      </script>
      <template lang="pug">div(v-fooBar)</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default {
        directives: {
          'foo-bar': {}
        }
      }
      </script>
      <template lang="pug">div(v-foo-bar)</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default {
        directives: {
          Focus: {}
        }
      }
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus>
      </template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-foo)
div(v-barfoobaz)
</template>`,
      options: [{ ignore: ['/foo/'] }]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-fooBar)
div(v-foo-bar)
</template>`,
      options: [{ ignore: ['foo-bar'] }]
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Element is missing end tag.
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus>
      </template>
      `,
      errors: [
        {
          message: "The 'v-focus' directive has been used, but not defined.",
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 21
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      const vfocus = {} // should be vFocus
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus>
      </template>
      `,
      errors: [
        {
          message: "The 'v-focus' directive has been used, but not defined.",
          line: 6,
          column: 14,
          endLine: 6,
          endColumn: 21
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import { foo as bar } from './foo'
      </script>
      <template lang="pug">div(v-foo)</template>
      `,
      errors: [
        {
          message: "The 'v-foo' directive has been used, but not defined.",
          line: 5,
          column: 32,
          endLine: 5,
          endColumn: 37
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import focus from './focus'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-focus>
      </template>
      `,
      errors: [
        {
          message: "The 'v-focus' directive has been used, but not defined.",
          line: 6,
          column: 14,
          endLine: 6,
          endColumn: 21
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vClickOutside from './vClickOutside'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-clickoutside>
      </template>
      `,
      errors: [
        {
          message:
            "The 'v-clickoutside' directive has been used, but not defined.",
          line: 6,
          column: 14,
          endLine: 6,
          endColumn: 28
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
      import vClickoutside from './vClickOutside'
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-click-outside>
      </template>
      `,
      errors: [
        {
          message:
            "The 'v-click-outside' directive has been used, but not defined.",
          line: 6,
          column: 14,
          endLine: 6,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(v-foo:[arg])</template>`,
      errors: [
        {
          message: "The 'v-foo' directive has been used, but not defined.",
          line: 2,
          column: 32,
          endLine: 2,
          endColumn: 43
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(v-foo.bar)</template>`,
      errors: [
        {
          message: "The 'v-foo' directive has been used, but not defined.",
          line: 2,
          column: 32,
          endLine: 2,
          endColumn: 41
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(v-foo:bar.baz)</template>`,
      errors: [
        {
          message: "The 'v-foo' directive has been used, but not defined.",
          line: 2,
          column: 32,
          endLine: 2,
          endColumn: 45
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default {
        directives: {
          focus: {}
        }
      }
      </script>
<!-- CONVERT ERROR -->Element is missing end tag.      <template>
        <div v-Focus>
      </template>
      `,
      errors: [
        {
          message: "The 'v-Focus' directive has been used, but not defined.",
          line: 10,
          column: 14,
          endLine: 10,
          endColumn: 21
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export default {
        directives: {
          foobar: {}
        }
      }
      </script>
      <template lang="pug">div(v-foo-bar)</template>
      `,
      errors: [
        {
          message: "The 'v-foo-bar' directive has been used, but not defined.",
          line: 9,
          column: 32,
          endLine: 9,
          endColumn: 41
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(v-foo-bar)</template>`,
      options: [{ ignore: ['baz'] }],
      errors: [
        {
          message: "The 'v-foo-bar' directive has been used, but not defined.",
          line: 2,
          column: 32,
          endLine: 2,
          endColumn: 41
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(v-foo-bar)</template>`,
      options: [{ ignore: ['/^bar/'] }],
      errors: [
        {
          message: "The 'v-foo-bar' directive has been used, but not defined.",
          line: 2,
          column: 32,
          endLine: 2,
          endColumn: 41
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-foo)
div(v-barfoobaz)
</template>`,
      options: [{ ignore: ['foo'] }],
      errors: [
        {
          message:
            "The 'v-barfoobaz' directive has been used, but not defined.",
          line: 4,
          column: 5,
          endLine: 4,
          endColumn: 16
        }
      ]
    }
  ]
})
