// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-undef-properties.test.ts
/**
 * @fileoverview Disallow undefined properties.
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-undef-properties'
import { getTypeScriptFixtureTestOptions } from '../../../../eslint-plugin-vue/tests/test-utils/typescript'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-undef-properties', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:attr="foo") {{ bar }}</template>
      <script>
        export default {
          props: ['foo'],
          data () {
            return {
              bar: 42
            }
          },
          created() {
            this.baz()
          },
          methods: {
            baz() {}
          }
        };
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:attr="foo") {{ bar }}</template>
      <script>
        export default {
          inject: ['foo'],
          setup() {
            return {
              bar: 42
            }
          },
          computed: {
            baz() {
              return 42
            }
          },
          created() {
            console.log(this.baz)
          }
        };
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div {{ foo }}</template>
      <script>
        export default {
          asyncData() {
            return {
              foo: 42
            }
          },
        };
      </script>`
    },
    //default ignores
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div {{ $t(&apos;foo&apos;) }}</template>
      <script>
        export default {
          mounted() {
            const hash = this.$route.hash
            this.$on('click', this.click)
          },
          methods: {
            click() {
              this.$nextTick()
            }
          }
        }
      </script>`
    },
    {
      // global in template
      filename: 'test.vue',
      code: `
      <template lang="pug">div {{ undefined }}</template>
      <script>
        export default {
        }
      </script>`
    },

    //watch
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          props: ['foo'],
          watch: {
            foo: 'bar'
          },
          methods: {
            bar() {}
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: {
                bar :42
              }
            }
          },
          watch: {
            'foo.bar': 'baz'
          },
          methods: {
            baz() {}
          }
        };
      </script>
      `
    },

    // props
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          props: ['foo'],
          data (props) {
            return {
              bar: props.foo
            }
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          props: ['foo'],
          setup (props) {
            return {
              bar: props.foo
            }
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          functional: true,
          props: ['foo'],
          render (_, {props}) {
            return h(props.foo)
          }
        };
      </script>
      `
    },

    // arg vm
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {return {foo:42}},
          render (vm) {
            return h(vm.foo)
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {return {foo:42}},
          computed: { p: (vm) => vm.foo }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {return {foo:42}},
          computed: { p: { get: (vm) => vm.foo } }
        };
      </script>
      `
    },

    // deep
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">| {{ foo.bar }}</template>
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: 42
              }
            }
          },
        };
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">| {{ foo.bar.baz }}</template>
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: {
                  baz: 42
                }
              }
            }
          },
        };
      </script>`
    },

    // track
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            fn(this)
          }
        };

        function fn(vm) {
          return vm.foo
        }
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        const fn = function(vm) {
          return vm.foo
        }
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            fn(this)
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        function a(vm) {
          return vm.foo
        }
        const fn = a
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            fn(this)
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        function a(vm) {
          return vm.foo2
        }
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            b(this)
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        function a(vm) {
          return vm.foo2
        }
        const b = unknown
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            b(this)
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        function a(vm) {
          return vm.foo2
        }
        let b = a
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            b(this)
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        function fn( { foo } = {} ) {
        }
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            fn(this)
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            const { foo = 42 } = this
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: 42
              }
            }
          },
          mounted() {
            const { foo : { bar = 42 } = {} } = this
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: 42
              }
            }
          },
          mounted() {
            ({ foo : { bar: v = 42 } = {} } = this)
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: 41
            }
          },
          mounted() {
            const vm = this
            vm.foo
          }
        };
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: 42
              }
            }
          },
          mounted() {
            const vm = this
            ;(vm?.foo)?.bar
          }
        };
      </script>
      `
    },

    // Vue2 functional component
    {
      filename: 'test.vue',
      code: `
      <template functional>
        <div>{{props.a}} {{props.b}}</div>
      </template>

      <script>
      export default {
        props: {
          a: String,
          b: String,
        },
      };
      </script>`
    },

    {
      // unknown type
      filename: 'test.vue',
      code: `
      <script setup lang="ts">
      import type { Props1 } from './test01';

      defineProps<Props1>();

      </script>

      <template lang="pug">
div {{ foo }}
div {{ unknown }}
</template>`,
      languageOptions: {
        parserOptions: {
          parser: require.resolve('@typescript-eslint/parser'),
          templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
        }
      }
    },
    {
      // Vuex
      filename: 'test.vue',
      code: `
      <script>
      import { mapState } from 'vuex';

      export default {
        computed: {
          ...mapState({
            a: (vm) => vm.a,
            b: (vm) => vm.b,
          })
        },
        methods: {
          c() {return this.a * this.b}
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapActions } from 'vuex';

      export default {
          methods: {
          ...mapActions({
            a: 'a',
            b: 'b',
          }),
          c() {return this.a()},
          d() {return this.b()},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapMutations } from 'vuex';

      export default {
          methods: {
          ...mapMutations({
            a: 'a',
            b: 'b',
          }),
          c() {return this.a()},
          d() {return this.b()},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapActions } from 'vuex';

      export default {
          methods: {
          ...mapActions(['a', 'b']),
          c() {return this.a()},
          d() {return this.b()},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapMutations } from 'vuex';

      export default {
        methods: {
          ...mapMutations(['a', 'b']),
          c() {return this.a()},
          d() {return this.b()},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapGetters } from 'vuex';

      export default {
        computed: {
          ...mapGetters(['a', 'b'])
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      // Pinia
      filename: 'test.vue',
      code: `
      <script>
      import { mapGetters } from 'pinia'
      import { useStore } from '../store'

      export default {
        computed: {
          ...mapGetters(useStore, ['a', 'b'])
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapState } from 'pinia'
      import { useStore } from '../store'

      export default {
        computed: {
          ...mapState(useStore, {
            a: 'a',
            b: store => store.b,
          })
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapWritableState } from 'pinia'
      import { useStore } from '../store'

      export default {
        computed: {
          ...mapWritableState(useStore, {
            a: 'a',
            b: 'b',
          })
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapWritableState } from 'pinia'
      import { useStore } from '../store'

      export default {
        computed: {
          ...mapWritableState(useStore, ['a', 'b'])
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapActions } from 'pinia'
      import { useStore } from '../store'

      export default {
          methods: {
          ...mapActions(useStore, ['a', 'b']),
          c() {return this.a()},
          d() {return this.b()},
        }
      }
      </script>
      <template lang="pug">
| {{ a() }}

| {{ b() }}
</template>
      `
    },
    `
    <script setup>
    const model = defineModel();
    const woof = computed(() => model.value);
    </script>
    <template lang="pug">
#app Woof:
  | {{ woof }}
</template>`
  ],

  invalid: [
    // undef property
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:attr="foo2") {{ bar2 }}</template>
      <script>
        export default {
          props: ['foo'],
          data () {
            return {
              bar: 42
            }
          },
          created() {
            this.baz2()
          },
          methods: {
            baz() {}
          }
        };
      </script>`,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 2,
          column: 39,
          endLine: 2,
          endColumn: 43
        },
        {
          message: "'bar2' is not defined.",
          line: 2,
          column: 49,
          endLine: 2,
          endColumn: 53
        },
        {
          message: "'baz2' is not defined.",
          line: 12,
          column: 18,
          endLine: 12,
          endColumn: 22
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:attr="foo2") {{ bar2 }}</template>
      <script>
        export default {
          inject: ['foo'],
          setup() {
            return {
              bar: 42
            }
          },
          computed: {
            baz() {
              return 42
            }
          },
          created() {
            console.log(this.baz2)
          }
        };
      </script>`,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 2,
          column: 39,
          endLine: 2,
          endColumn: 43
        },
        {
          message: "'bar2' is not defined.",
          line: 2,
          column: 49,
          endLine: 2,
          endColumn: 53
        },
        {
          message: "'baz2' is not defined.",
          line: 17,
          column: 30,
          endLine: 17,
          endColumn: 34
        }
      ]
    },

    // same names
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:attr="foo2") {{ foo2 }}</template>
      <script>
        export default {
          props: ['foo'],
          created() {
            this.foo2

            this.foo2
          }
        };
      </script>`,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 7,
          column: 18,
          endLine: 7,
          endColumn: 22
        }
      ]
    },

    //watch
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          props: ['foo'],
          watch: {
            foo2: 'bar2'
          },
          methods: {
            bar() {}
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 6,
          column: 13,
          endLine: 6,
          endColumn: 17
        },
        {
          message: "'bar2' is not defined.",
          line: 6,
          column: 19,
          endLine: 6,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: {
                bar :42
              }
            }
          },
          watch: {
            'foo2.bar': 'baz',
            'foo.bar2': 'baz',
          },
          methods: {
            baz() {}
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 12,
          column: 13,
          endLine: 12,
          endColumn: 23
        },
        {
          message: "'foo.bar2' is not defined.",
          line: 13,
          column: 13,
          endLine: 13,
          endColumn: 23
        }
      ]
    },

    // props
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          computed: {
            foo () {}
          },
          data (props) {
            return {
              bar: props.foo
            }
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo' is not defined in props.",
          line: 9,
          column: 26,
          endLine: 9,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          computed: {
            foo () {}
          },
          setup (props) {
            return {
              bar: props.foo
            }
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo' is not defined in props.",
          line: 9,
          column: 26,
          endLine: 9,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          functional: true,
          computed: {
            foo () {}
          },
          render (_, {props}) {
            return h(props.foo)
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo' is not defined in props.",
          line: 9,
          column: 28,
          endLine: 9,
          endColumn: 31
        }
      ]
    },

    // arg vm
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {return {foo:42}},
          render (vm) {
            return h(vm.bar)
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'bar' is not defined.",
          line: 6,
          column: 25,
          endLine: 6,
          endColumn: 28
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {return {foo:42}},
          computed: { p: (vm) => vm.bar }
        };
      </script>
      `,
      errors: [
        {
          message: "'bar' is not defined.",
          line: 5,
          column: 37,
          endLine: 5,
          endColumn: 40
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {return {foo:42}},
          computed: { p: { get: (vm) => vm.bar } }
        };
      </script>
      `,
      errors: [
        {
          message: "'bar' is not defined.",
          line: 5,
          column: 44,
          endLine: 5,
          endColumn: 47
        }
      ]
    },

    // deep
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">| {{ foo.baz }}</template>
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: 42
              }
            }
          },
        };
      </script>`,
      errors: [
        {
          message: "'foo.baz' is not defined.",
          line: 2,
          column: 37,
          endLine: 2,
          endColumn: 40
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">| {{ foo.bar.baz2 }}</template>
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: {
                  baz: 42
                }
              }
            }
          },
        };
      </script>`,
      errors: [
        {
          message: "'foo.bar.baz2' is not defined.",
          line: 2,
          column: 41,
          endLine: 2,
          endColumn: 45
        }
      ]
    },

    // track
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            fn(this)
          }
        };

        function fn(vm) {
          return vm.foo2
        }
      </script>
      `,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 15,
          column: 21,
          endLine: 15,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        const fn = function(vm) {
          return vm.foo2
        }
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            fn(this)
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 4,
          column: 21,
          endLine: 4,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        function a(vm) {
          return vm.foo2
        }
        const fn = a
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            fn(this)
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 4,
          column: 21,
          endLine: 4,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        function fn( { foo2 } = {} ) {
        }
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            fn(this)
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 3,
          column: 24,
          endLine: 3,
          endColumn: 28
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: 42
            }
          },
          mounted() {
            const { foo2 = 42 } = this
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 10,
          column: 21,
          endLine: 10,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: 42
              }
            }
          },
          mounted() {
            const { foo : { bar2 = 42 } = {} } = this
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo.bar2' is not defined.",
          line: 12,
          column: 29,
          endLine: 12,
          endColumn: 33
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: 42
              }
            }
          },
          mounted() {
            ({ foo : { bar2: v = 42 } = {} } = this)
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo.bar2' is not defined.",
          line: 12,
          column: 24,
          endLine: 12,
          endColumn: 28
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: 41
            }
          },
          mounted() {
            const vm = this
            vm.foo2
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo2' is not defined.",
          line: 11,
          column: 16,
          endLine: 11,
          endColumn: 20
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          data () {
            return {
              foo: {
                bar: 42
              }
            }
          },
          mounted() {
            const vm = this
            ;(vm?.foo)?.bar2
          }
        };
      </script>
      `,
      errors: [
        {
          message: "'foo.bar2' is not defined.",
          line: 13,
          column: 25,
          endLine: 13,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
// ✓ GOOD
div {{ name }}
  | :
  | {{ count }}
// ✗ BAD
div {{ label }}
  | :
  | {{ cnt }}
</template>
      <script setup>
      const prop = defineProps(['name', 'def'])
      let count = 0

      /* ✓ GOOD */
      watch(() => prop.def, () => console.log('Updated!'))

      /* ✗ BAD */
      watch(() => prop.undef, () => console.log('Updated!'))
      </script>`,
      errors: [
        {
          message: "'label' is not defined.",
          line: 8,
          column: 8,
          endLine: 8,
          endColumn: 13
        },
        {
          message: "'cnt' is not defined.",
          line: 10,
          column: 8,
          endLine: 10,
          endColumn: 11
        },
        {
          message: "'undef' is not defined.",
          line: 20,
          column: 24,
          endLine: 20,
          endColumn: 29
        }
      ]
    },

    // Vue2 functional component
    {
      filename: 'test.vue',
      code: `
      <template functional>
        <div>{{props.a}} {{props.b}} {{props.c}}</div>
      </template>

      <script>
      export default {
        props: {
          a: String,
          b: String,
        },
      };
      </script>`,
      errors: [
        {
          message: "'c' is not defined.",
          line: 3,
          column: 46,
          endLine: 3,
          endColumn: 47
        }
      ]
    },

    {
      // known type
      code: `
      <script setup lang="ts">
      import type { Props1 } from './test01';

      defineProps<Props1>();

      </script>

      <template lang="pug">
div {{ foo }}
div {{ unknown }}
</template>`,
      errors: [
        {
          message: "'unknown' is not defined.",
          line: 3,
          column: 18,
          endLine: 11,
          endColumn: 22
        }
      ],
      ...getTypeScriptFixtureTestOptions()
    },

    {
      // defineModel
      filename: 'test.vue',
      code: `
      <script setup>
      const m = defineModel()
      const a = defineModel('A')
      const [withModifiers, modifiers] = defineModel('withModifiers')
      </script>
      <template lang="pug">
div {{ m }}

  | {{ modelValue }}

  | {{ a }}

  | {{ A }}

  | {{withModifiers}}

  | {{modifiers}}
div {{ undef }}
</template>
      `,
      errors: [
        {
          message: "'undef' is not defined.",
          line: 19,
          column: 8,
          endLine: 19,
          endColumn: 13
        }
      ]
    },
    {
      // Vuex
      filename: 'test.vue',
      code: `
      <script>
      import { mapState } from 'vuex';

      export default {
        computed: {
          ...mapState({
            a: (vm) => vm.a,
            b: (vm) => vm.b,
          })
        },
        methods: {
          c() {return this.a * this.g}
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}

| {{ c }}
</template>
      `,
      errors: [
        {
          message: "'g' is not defined.",
          line: 13,
          column: 37,
          endLine: 13,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapActions } from 'vuex';

      export default {
          methods: {
          ...mapActions({
            a: 'a',
            b: 'b',
          }),
          c() {return this.a()},
          d() {return this.f()},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `,
      errors: [
        {
          message: "'f' is not defined.",
          line: 12,
          column: 28,
          endLine: 12,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapMutations } from 'vuex';

      export default {
          methods: {
          ...mapMutations({
            a: 'a',
            b: 'b',
          }),
          c() {return this.a()},
          d() {return this.b()},
          d() {return this.x()},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `,
      errors: [
        {
          message: "'x' is not defined.",
          line: 13,
          column: 28,
          endLine: 13,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapActions } from 'vuex';

      export default {
          methods: {
          ...mapActions(['a', 'b']),
          c() {return this.a()},
          d() {return this.b()},
          d() {return this.f()},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `,
      errors: [
        {
          message: "'f' is not defined.",
          line: 10,
          column: 28,
          endLine: 10,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapMutations } from 'vuex';

      export default {
        methods: {
          ...mapMutations(['a', 'b']),
          c() {return this.a()},
          d() {return this.b()},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}

| {{ q }}
</template>
      `,
      errors: [
        {
          message: "'q' is not defined.",
          line: 18,
          column: 6,
          endLine: 18,
          endColumn: 7
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapGetters } from 'vuex';

      export default {
        computed: {
          ...mapGetters(['a', 'b'])
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
          d() {return this.z},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `,
      errors: [
        {
          message: "'z' is not defined.",
          line: 12,
          column: 28,
          endLine: 12,
          endColumn: 29
        }
      ]
    },
    {
      // Pinia
      filename: 'test.vue',
      code: `
      <script>
      import { mapGetters } from 'pinia'
      import { useStore } from '../store'

      export default {
        computed: {
          ...mapGetters(useStore, ['a', 'b'])
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
          d() {return this.z},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `,
      errors: [
        {
          message: "'z' is not defined.",
          line: 13,
          column: 28,
          endLine: 13,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapState } from 'pinia'
      import { useStore } from '../store'

      export default {
        computed: {
          ...mapState(useStore, {
            a: 'a',
            b: store => store.b,
          })
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}

| {{ q }}
</template>
      `,
      errors: [
        {
          message: "'q' is not defined.",
          line: 24,
          column: 6,
          endLine: 24,
          endColumn: 7
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapWritableState } from 'pinia'
      import { useStore } from '../store'

      export default {
        computed: {
          ...mapWritableState(useStore, {
            a: 'a',
            b: 'b',
          })
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
          d() {return this.z},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `,
      errors: [
        {
          message: "'z' is not defined.",
          line: 16,
          column: 28,
          endLine: 16,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapWritableState } from 'pinia'
      import { useStore } from '../store'

      export default {
        computed: {
          ...mapWritableState(useStore, ['a', 'b'])
        },
        methods: {
          c() {return this.a},
          d() {return this.b},
          d() {return this.z},
        }
      }
      </script>
      <template lang="pug">
| {{ a }}

| {{ b }}
</template>
      `,
      errors: [
        {
          message: "'z' is not defined.",
          line: 13,
          column: 28,
          endLine: 13,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { mapActions } from 'pinia'
      import { useStore } from '../store'

      export default {
          methods: {
          ...mapActions(useStore, ['a', 'b']),
          c() {return this.a()},
          d() {return this.b()},
          d() {return this.x()},
        }
      }
      </script>
      <template lang="pug">
| {{ a() }}

| {{ b() }}
</template>
      `,
      errors: [
        {
          message: "'x' is not defined.",
          line: 11,
          column: 28,
          endLine: 11,
          endColumn: 29
        }
      ]
    }
  ]
})
