// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-unused-components.test.ts
/**
 * @fileoverview Report used components
 * @author Michał Sajnóg
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-unused-components'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2018,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-unused-components', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div Lorem ipsum</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  h2 Lorem ipsum
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  TheButton
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg
  TheCircle
</template>
      <script>
        export default {
          components: {
            TheCircle
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">circle(cx="0", cy="0", :d="radius")</template>
      <script>
        export default {}
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  component(:is="'TheButton'")
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  component(is="TheButton")
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  theButton
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  component(is="theButton")
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  the-button
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  the-button
</template>
      <script>
        export default {
          components: {
            theButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  component(is="the-button")
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  The-button
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  component(is="The-button")
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  The-Button
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  component(is="The-Button")
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  the-Button
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  component(is="the-Button")
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  the-button
  next_Button
</template>
      <script>
        export default {
          components: {
            'the-button': TheButton,
            'next_Button': NextButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  component(is="the-button")
  component(is="next_Button")
</template>
      <script>
        export default {
          components: {
            'the-button': TheButton,
            'next_Button': NextButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  h2 Lorem ipsum
  component(is="TheButton")
</template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
#app
  Header
  .content
    router-view
  Footer
</template>
      <script>
        import Header from 'components/Layout/Header';
        import Footer from 'components/Layout/Footer';

        export default {
          name: 'App',
          components: {
            Header,
            Footer,
          },
        };
      </script>`
    },

    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div
  component(:is="dynamicComponent")
</template>
      <script>
        import Foo from 'components/Foo';
        import Bar from 'components/Bar';

        export default {
          components: {
            Foo,
            Bar
          },
          computed: {
            dynamicComponent() {
              return '...'
            }
          }
        }
      </script>`,
      options: [{ ignoreWhenBindingPresent: true }]
    },

    // Ignore when `render` is used instead of template
    {
      filename: 'test.vue',
      code: `
      <script>
        export default {
          components: {
            TheButton
          },
          render() {
            return
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <template src="./test.html" />
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <template src="./test.html"></template>
      <script>
        export default {
          components: {
            TheButton
          }
        }
      </script>`
    },

    // empty `:is`
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">component(:is=)</template>`
    },

    // computed properties
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div</template>
      <script>
        export default {
          components: {
            [foo.bar]: baz
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div</template>
      <script>
        export default {
          components: {
            [foo]: Bar
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">foo</template>
      <script>
        export default {
          components: {
            ['foo']: Foo
          }
        }
      </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">div(v-is="'CustomComponent'")</template>
        <script>
        export default {
          components: {
            CustomComponent
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">div(is="vue:CustomComponent")</template>
        <script>
        export default {
          components: {
            CustomComponent
          }
        }
        </script>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  h2 Lorem ipsum
</template>
        <script>
          export default {
            components: {
              TheButton
            },
          }
        </script>`,
      errors: [
        {
          message:
            'The "TheButton" component has been registered but not used.',
          line: 9,
          column: 15,
          endLine: 9,
          endColumn: 24
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  h2 Lorem ipsum
  the_button
</template>
        <script>
          export default {
            components: {
              TheButton
            },
          }
        </script>`,
      errors: [
        {
          message:
            'The "TheButton" component has been registered but not used.',
          line: 10,
          column: 15,
          endLine: 10,
          endColumn: 24
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  h2 Lorem ipsum
  TheButton
</template>
        <script>
          export default {
            components: {
              'the-button': TheButton
            },
          }
        </script>`,
      errors: [
        {
          message:
            'The "the-button" component has been registered but not used.',
          line: 10,
          column: 15,
          endLine: 10,
          endColumn: 38
        }
      ]
    },
    // Setting: ignoreWhenBindingPresent
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div
  component(:is="dynamicComponent")
</template>
      <script>
        import Foo from 'components/Foo';
        import Bar from 'components/Bar';

        export default {
          components: {
            Foo,
            Bar
          },
          computed: {
            dynamicComponent() {
              return '...'
            }
          }
        }
      </script>`,
      options: [{ ignoreWhenBindingPresent: false }],
      errors: [
        {
          message: 'The "Foo" component has been registered but not used.',
          line: 12,
          column: 13,
          endLine: 12,
          endColumn: 16
        },
        {
          message: 'The "Bar" component has been registered but not used.',
          line: 13,
          column: 13,
          endLine: 13,
          endColumn: 16
        }
      ]
    },

    // empty `:is`
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">component(:is=)</template>
      <script>
        export default {
          components: {
            Foo,
          },
        }
      </script>`,
      errors: [
        {
          message: 'The "Foo" component has been registered but not used.',
          line: 6,
          column: 13,
          endLine: 6,
          endColumn: 16
        }
      ]
    },

    // computed properties
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div</template>
      <script>
        export default {
          components: {
            ['foo']: Foo,
            [\`bar\`]: Bar,
            ['baz']: Baz,
            [qux]: Qux,
            ...components,
            quux,
          }
        }
      </script>`,
      errors: [
        {
          message: 'The "foo" component has been registered but not used.',
          line: 6,
          column: 13,
          endLine: 6,
          endColumn: 25
        },
        {
          message: 'The "bar" component has been registered but not used.',
          line: 7,
          column: 13,
          endLine: 7,
          endColumn: 25
        },
        {
          message: 'The "baz" component has been registered but not used.',
          line: 8,
          column: 13,
          endLine: 8,
          endColumn: 25
        },
        {
          message: 'The "quux" component has been registered but not used.',
          line: 11,
          column: 13,
          endLine: 11,
          endColumn: 17
        }
      ]
    },

    // Many components and one in middle is no present
    {
      filename: 'test.vue',
      // upstream uses the dotted component name `fio.fio`; pug parses
      // `fio.fio` as `<fio class="fio">`, so the dotted name is renamed
      // to `Fio` here.
      code: `
        <template lang="pug">
div
  Foo
  Fio
  baz
</template>
        <script>
          export default {
            components: {
              Foo,
              Fio,
              Bar,
              Baz
            },
          }
        </script>`,
      errors: [
        {
          message: 'The "Bar" component has been registered but not used.',
          line: 13,
          column: 15,
          endLine: 13,
          endColumn: 18
        }
      ]
    }
  ]
})
