// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-useless-mustaches.test.ts
/**
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-useless-mustaches'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module'
  }
})

tester.run('no-useless-mustaches', rule, {
  valid: [
    `
    <template lang="pug">
| foo &apos;foo&apos;
| {{ foo }}

| {{ &apos;foo&apos;||&apos;bar&apos; }}

| {{ 1 }}

| {{  }}

| {{ . }}

| {{ null }}
</template>`,
    {
      code: `
      <template lang="pug">
| {{ &apos;comment&apos;/*comment*/ }}

| {{ &apos;comment&apos;//comment
| &quot; }}
</template>`,
      options: [{ ignoreIncludesComment: true }]
    },
    {
      code: String.raw`
      <template lang="pug">
| {{ &apos;\n&apos; }}

| {{ &apos;\r&apos; }}
</template>`,
      options: [{ ignoreStringEscape: true }]
    }
  ],
  invalid: [
    {
      code: `
      <template lang="pug">| {{ &apos;foo&apos; }}</template>`,
      output: `
      <template lang="pug">| foo</template>`,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 20
        }
      ]
    },
    {
      code: `
      <template lang="pug">
| {{ &apos;comment&apos;/*comment*/ }}

| {{ &apos;comment&apos;//comment
| }}
</template>`,
      output: null,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 35
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 4,
          column: 9,
          endLine: 5,
          endColumn: 12
        }
      ]
    },
    {
      code: String.raw`
      <template lang="pug">
| {{ &apos;\n&apos; }}

| {{ &apos;\r&apos; }}
</template>`,
      output: null,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 19
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 19
        }
      ]
    },
    {
      code: `
      <template lang="pug">
| {{ &apos;&amp;quot;&apos; }}

| {{ \`&amp;quot;&amp;apos;\` }}

| {{ &apos;\\\\&apos; }}

| {{ &apos;\\\\r&apos; }}

| {{ &apos;\\&apos; }}

| {{ \`foo\` }}

| {{ \`foo\${bar}\` }}

| {{ &quot;&amp;apos;&quot; }}

| {{ \`foo\` }}
</template>`,
      output: `
      <template lang="pug">
| &quot; &quot;&apos; \\ \\r
| {{ &apos;\\&apos; }}
| foo
| {{ \`foo\${bar}\` }}
| &apos; foo
</template>`,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 23
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 29
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 19
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 6,
          column: 9,
          endLine: 6,
          endColumn: 20
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 8,
          column: 9,
          endLine: 8,
          endColumn: 20
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 10,
          column: 9,
          endLine: 10,
          endColumn: 23
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 11,
          column: 9,
          endLine: 11,
          endColumn: 20
        }
      ]
    },
    {
      code: `
      <template lang="pug">
| {{ &amp;apos;msg&amp;apos; }}

| {{ &amp;quot;msg&amp;quot; }}

| {{ &amp;apos;msg&apos; }}

| {{ &amp;quot;msg&quot; }}

| {{ &apos;msg&amp;apos; }}

| {{ &quot;msg&amp;quot; }}

| {{ &amp;#39;&amp;lt;msg&amp;gt;&amp;apos; }}

| {{ &amp;#34;I&amp;apos;m&amp;#x22; }}

| {{ &quot;no semi&amp;#34 }}
</template>`,
      output: `
      <template lang="pug">
| msg msg msg msg msg msg &lt;msg&gt; I&apos;m
| {{ &quot;no semi&amp;#34 }}
</template>`,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 30
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 30
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 25
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 6,
          column: 9,
          endLine: 6,
          endColumn: 25
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 7,
          column: 9,
          endLine: 7,
          endColumn: 25
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 8,
          column: 9,
          endLine: 8,
          endColumn: 25
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 9,
          column: 9,
          endLine: 9,
          endColumn: 37
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 10,
          column: 9,
          endLine: 10,
          endColumn: 34
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 11,
          column: 9,
          endLine: 11,
          endColumn: 27
        }
      ]
    },
    {
      code: `
      <template lang="pug">
| {{ &apos;I\\&apos;m&apos; }}

| {{ &quot;\\&quot;Happy\\&quot;&quot; }}

| {{ \`backtick \\\` and dollar $\` }}

| {{ &quot;\\\\&quot; }}
</template>`,
      output: `
      <template lang="pug">| I&apos;m &quot;Happy&quot; backtick \` and dollar $ \\</template>`,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 21
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 26
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 42
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 6,
          column: 9,
          endLine: 6,
          endColumn: 19
        }
      ]
    },
    {
      code: `
      <template lang="pug">
| {{ &apos;&amp;lt;&apos; }}

| {{ &apos;&amp;gt;&apos; }}

| {{ &apos;&amp;amp;&apos; }}

| {{ &apos;&amp;#8212;&apos; }}
</template>`,
      output: `
      <template lang="pug">| &lt; &gt; &amp; —</template>`,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 21
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 21
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 22
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 6,
          column: 9,
          endLine: 6,
          endColumn: 24
        }
      ]
    },
    {
      code: `
      <template lang="pug">
| {{ &apos;&lt;&apos; }}

| {{ &apos;&lt;&lt;&apos; }}

| {{ &apos;can be &lt; anywhere&apos; }}

| {{ &apos;&lt;tag&gt;&apos; }}
</template>`,
      output: `
      <template lang="pug">| &lt; &lt;&lt; can be &lt; anywhere &lt;tag&gt;</template>`,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 18
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 19
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 34
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 6,
          column: 9,
          endLine: 6,
          endColumn: 22
        }
      ]
    },
    {
      code: `
      <template lang="pug">
| {{ \`foo
| bar\` }}
</template>`,
      output: null,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 4,
          endColumn: 8
        }
      ]
    },
    {
      code: `
      <template lang="pug">
| {{ &apos;space &apos; }}

| {{ &apos; space&apos; }}

| {{ &apos; space &apos; }}

| {{ &apos;  &apos; }}
</template>`,
      output: null,
      errors: [
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 3,
          column: 9,
          endLine: 3,
          endColumn: 23
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 23
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 24
        },
        {
          message:
            'Unexpected mustache interpolation with a string literal value.',
          line: 6,
          column: 9,
          endLine: 6,
          endColumn: 19
        }
      ]
    }
  ]
})
