// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-v-for-template-key-on-child.test.ts
/**
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-v-for-template-key-on-child'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('no-v-for-template-key-on-child', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list")
    Foo
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key="x")
    Foo
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key="x.id")
    Foo(:key="x.id")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="(x, i) in list", :key="i")
    Foo(:key="x")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="(x, i) in list")
    Foo(:key="foo")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div
  template(v-for="x in list")
    Foo(v-if="a", :key="x")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div
  template(v-for="x in list")
    Foo(v-if="a", :key="x.key1")
    Foo(v-else-if="a", :key="x.key2")
    Foo(v-else, :key="x.key3")
    Foo(v-for="y in list", :key="x.key4")
</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list")
    Foo(:key="x")
</template>`,
      errors: [
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 17
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list")
    Foo(:key="x.id")
</template>`,
      errors: [
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 20
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key="foo")
    Foo(:key="x.id")
</template>`,
      errors: [
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 20
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key)
    Foo(:key="x.id")
</template>`,
      errors: [
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 20
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key)
    div
    Foo(:key="x.id")
</template>`,
      errors: [
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 20
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key)
    Foo(:key="'foo' + x.id")
    Bar(:key="'bar' + x.id")
</template>`,
      errors: [
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 28
        },
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 28
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div
  template(v-for="x in list")
    Foo(v-if="a", :key="x.key1")
    Foo(v-else-if="a", :key="x.key2")
    Foo(v-else, :key="x.key3")
    Foo(v-for="y in list", :key="x.key4")
    Foo(:key="x.error1")
    div(:key="x.error2")
    slot(:key="x.error3")
</template>`,
      errors: [
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 9,
          column: 9,
          endLine: 9,
          endColumn: 24
        },
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 10,
          column: 9,
          endLine: 10,
          endColumn: 24
        },
        {
          message:
            '`<template v-for>` key should be placed on the `<template>` tag.',
          line: 11,
          column: 10,
          endLine: 11,
          endColumn: 25
        }
      ]
    }
  ]
})
