// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/no-v-text-v-html-on-component.test.ts
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/no-v-text-v-html-on-component'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module'
  }
})

tester.run('no-v-text-v-html-on-component', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(v-text="content")</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(v-html="content")</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">MyComponent(v-if="content")</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">router-link(v-text="content")</template>`,
      options: [{ allow: ['router-link'] }]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
router-link(v-html="content")
NuxtLink(v-html="content")
</template>`,
      options: [{ allow: ['RouterLink', 'nuxt-link'] }]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
svg
  g(v-text="content")
math
  mspace(v-text="content")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
h1(v-html="content")
g(v-text="content")
mi(v-text="content")
</template>`,
      options: [{ ignoreElementNamespaces: true }]
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">MyComponent(v-text="content")</template>`,
      errors: [
        {
          message: "Using v-text on component may break component's content.",
          line: 3,
          column: 22,
          endLine: 3,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">MyComponent(v-html="content")</template>`,
      errors: [
        {
          message: "Using v-html on component may break component's content.",
          line: 3,
          column: 22,
          endLine: 3,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">component(:is="component", v-text="content")</template>`,
      errors: [
        {
          message: "Using v-text on component may break component's content.",
          line: 3,
          column: 36,
          endLine: 3,
          endColumn: 52
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">component(:is="component", v-html="content")</template>`,
      errors: [
        {
          message: "Using v-html on component may break component's content.",
          line: 3,
          column: 36,
          endLine: 3,
          endColumn: 52
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:is="component", v-text="content")</template>`,
      errors: [
        {
          message: "Using v-text on component may break component's content.",
          line: 3,
          column: 30,
          endLine: 3,
          endColumn: 46
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:is="component", v-html="content")</template>`,
      errors: [
        {
          message: "Using v-html on component may break component's content.",
          line: 3,
          column: 30,
          endLine: 3,
          endColumn: 46
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">router-link(v-html="content")</template>`,
      options: [{ allow: ['nuxt-link'] }],
      errors: [
        {
          message: "Using v-html on component may break component's content.",
          line: 3,
          column: 22,
          endLine: 3,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
g(v-text="content")
mi(v-text="content")
</template>`,
      options: [{ ignoreElementNamespaces: false }],
      errors: [
        {
          message: "Using v-text on component may break component's content.",
          line: 3,
          column: 12,
          endLine: 3,
          endColumn: 28
        },
        {
          message: "Using v-text on component may break component's content.",
          line: 4,
          column: 13,
          endLine: 4,
          endColumn: 29
        }
      ]
    }
  ]
})
