// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/object-curly-newline.test.ts
/**
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/object-curly-newline'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: { parser: vueEslintParser, ecmaVersion: 2020 }
})

tester.run('object-curly-newline', rule, {
  valid: [
    `
    <template lang="pug">div(:foo="{a: 1}")</template>`,
    {
      code: `
      <template lang="pug">div(:foo="{a: 1}")</template>`,
      options: ['never']
    },
    `
    <template lang="pug">
div(:foo=\`{
  a: 1
}\`)
</template>`,
    {
      code: `
      <template lang="pug">
div(:foo=\`{
  a: 1
}\`)
</template>`,
      options: ['always']
    },
    `
    <template lang="pug">div(:[{a:1}]="value")</template>`,
    {
      code: `
      <template lang="pug">div(:[{a:1}]="value")</template>`,
      options: ['always']
    },
    {
      code: `
      <template lang="pug">div(:[{a:1}]="value")</template>`,
      options: ['never']
    }
  ],
  invalid: [
    {
      code: `
      <template lang="pug">
div(:foo=\`{a: 1
}\`)
</template>`,
      output: `
      <template lang="pug">div(:foo="{a: 1}")</template>`,
      errors: [
        {
          message: 'Unexpected line break before this closing brace.',
          line: 4,
          column: 9,
          endLine: 4,
          endColumn: 10
        }
      ]
    },
    {
      code: `
      <template lang="pug">
div(:foo=\`{
a: 1}\`)
</template>`,
      output: `
      <template lang="pug">div(:foo="{a: 1}")</template>`,
      errors: [
        {
          message: 'Unexpected line break after this opening brace.',
          line: 3,
          column: 20,
          endLine: 3,
          endColumn: 21
        }
      ]
    },
    {
      code: `
      <template lang="pug">div(:foo="{a: 1}")</template>`,
      output: `
      <template lang="pug">
div(:foo=\`{
a: 1
}\`)
</template>`,
      options: ['always'],
      errors: [
        {
          message: 'Expected a line break after this opening brace.',
          line: 3,
          column: 20,
          endLine: 3,
          endColumn: 21
        },
        {
          message: 'Expected a line break before this closing brace.',
          line: 3,
          column: 25,
          endLine: 3,
          endColumn: 26
        }
      ]
    },
    {
      code: `
      <template lang="pug">
div(:foo=\`{
  a: 1
}\`)
</template>`,
      output: `
      <template lang="pug">div(:foo="{a: 1}")</template>`,
      options: ['never'],
      errors: [
        {
          message: 'Unexpected line break after this opening brace.',
          line: 3,
          column: 20,
          endLine: 3,
          endColumn: 21
        },
        {
          message: 'Unexpected line break before this closing brace.',
          line: 5,
          column: 9,
          endLine: 5,
          endColumn: 10
        }
      ]
    }
  ]
})
