// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/object-shorthand.test.ts
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/object-shorthand'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module'
  }
})

tester.run('object-shorthand', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:style="{height}")</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:style="{height: height}")</template>`,
      options: ['never']
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:style="{height: height}")</template>`,
      output: `
      <template lang="pug">div(:style="{height}")</template>`,
      errors: [
        {
          message: 'Expected property shorthand.',
          line: 3,
          column: 23,
          endLine: 3,
          endColumn: 37
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:style="{height}")</template>`,
      output: `
      <template lang="pug">div(:style="{height: height}")</template>`,
      options: ['never'],
      errors: [
        {
          message: 'Expected longform property syntax.',
          line: 3,
          column: 23,
          endLine: 3,
          endColumn: 29
        }
      ]
    }
  ]
})
