// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/operator-linebreak.test.ts
/**
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/operator-linebreak'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('operator-linebreak', rule, {
  valid: [
    `
    <template lang="pug">div(:foo="1 + 2")</template>`,
    {
      code: `
      <template lang="pug">div(:foo="1 + 2")</template>`,
      options: ['before']
    },
    {
      code: `
      <template lang="pug">div(:foo="1 + 2")</template>`,
      options: ['none']
    },
    `
    <template lang="pug">div(:[foo+bar]="value")</template>`,
    {
      code: `
      <template lang="pug">div(:[foo+bar]="value")</template>`,
      options: ['before']
    },
    {
      code: `
      <template lang="pug">div(:[foo+bar]="value")</template>`,
      options: ['none']
    }
  ],
  invalid: [
    {
      code: `
      <template lang="pug">
div(:foo=\`1
+ 2\`)
</template>`,
      output: `
      <template lang="pug">
div(:foo=\`1 +
2\`)
</template>`,
      errors: [
        {
          message: "'+' should be placed at the end of the line.",
          line: 4,
          column: 1,
          endLine: 4,
          endColumn: 2
        }
      ]
    },
    {
      code: `
      <template lang="pug">
div(:foo=\`1 +
2\`)
</template>`,
      output: `
      <template lang="pug">
div(:foo=\`1
+ 2\`)
</template>`,
      options: ['before'],
      errors: [
        {
          message: "'+' should be placed at the beginning of the line.",
          line: 3,
          column: 13,
          endLine: 3,
          endColumn: 14
        }
      ]
    },
    {
      code: `
      <template lang="pug">
div(:foo=\`1 +
  2\`)
div(:foo=\`1
  + 2\`)
</template>`,
      output: `
      <template lang="pug">
div(:foo="1 +          2")
div(:foo="1          + 2")
</template>`,
      options: ['none'],
      errors: [
        {
          message: "There should be no line break before or after '+'.",
          line: 3,
          column: 13,
          endLine: 3,
          endColumn: 14
        },
        {
          message: "There should be no line break before or after '+'.",
          line: 6,
          column: 3,
          endLine: 6,
          endColumn: 4
        }
      ]
    }
  ]
})
