// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/prefer-template.test.ts
/**
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/prefer-template'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('prefer-template', rule, {
  valid: [
    `
    <template lang="pug">div(:class="[\`foo-\${bar}\`]")</template>`,
    `
    <template lang="pug">div(:[\`foo\${bar}\`]="value")</template>`,
    // CSS vars injection
    `
    <style>
    .text {
      color: v-bind('\`#\${hex}\`')
    }
    </style>`
  ],
  invalid: [
    {
      code: `
      <template lang="pug">div(:class="['foo-' + bar]")</template>`,
      output: `
      <template lang="pug">div(:class="[\`foo-\${  bar}\`]")</template>`,
      errors: [
        {
          message: 'Unexpected string concatenation.',
          line: 2,
          column: 41,
          endLine: 2,
          endColumn: 53
        }
      ]
    },
    {
      code: `
      <template lang="pug">div(:['foo'+bar]="value")</template>`,
      output: `
      <template lang="pug">div(:[\`foo\${bar}\`]="value")</template>`,
      errors: [
        {
          message: 'Unexpected string concatenation.',
          line: 2,
          column: 34,
          endLine: 2,
          endColumn: 43
        }
      ]
    },
    // CSS vars injection
    {
      code: `
      <style>
      .text {
        color: v-bind('"#"+hex')
      }
      </style>`,
      output: `
      <style>
      .text {
        color: v-bind('\`#\${hex}\`')
      }
      </style>`,
      errors: [
        {
          message: 'Unexpected string concatenation.',
          line: 4,
          column: 24,
          endLine: 4,
          endColumn: 31
        }
      ]
    }
  ]
})
