// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/quote-props.test.ts
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/quote-props'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('quote-props', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:style="{'height': '100vh'}")</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">div(:style="{height: '100vh'}")</template>`,
      options: ['as-needed']
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).
<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).      <template>
        <div :style="{height: '100vh'}"></div>
        <div :style='{height: "100vh"}'></div>
        <div :style={height:"100vh"}></div>
      </template>
      `,
      output: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).
<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).      <template>
        <div :style="{'height': '100vh'}"></div>
        <div :style='{"height": "100vh"}'></div>
        <div :style={"height":"100vh"}></div>
      </template>
      `,
      errors: [
        {
          message: "Unquoted property 'height' found.",
          line: 3,
          column: 23,
          endLine: 3,
          endColumn: 38
        },
        {
          message: "Unquoted property 'height' found.",
          line: 4,
          column: 23,
          endLine: 4,
          endColumn: 38
        },
        {
          message: "Unquoted property 'height' found.",
          line: 5,
          column: 22,
          endLine: 5,
          endColumn: 36
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(:style="{'height': '100vh'}")
div(:style='{"height": "100vh"}')
</template>`,
      output: `
      <template lang="pug">
div(:style="{height: '100vh'}")
div(:style='{height: "100vh"}')
</template>`,
      options: ['as-needed'],
      errors: [
        {
          message: "Unnecessarily quoted property 'height' found.",
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 31
        },
        {
          message: "Unnecessarily quoted property 'height' found.",
          line: 4,
          column: 14,
          endLine: 4,
          endColumn: 31
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">| {{ ({foo:42}).foo }}</template>`,
      output: `
      <template lang="pug">| {{ ({"foo":42}).foo }}</template>`,
      errors: [
        {
          message: "Unquoted property 'foo' found.",
          line: 2,
          column: 35,
          endLine: 2,
          endColumn: 41
        }
      ]
    }
  ]
})
