// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/require-toggle-inside-transition.test.ts
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/require-toggle-inside-transition'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('require-toggle-inside-transition', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  div(v-if="show")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  div(v-show="show")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
Transition
  div(v-if="show")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
Transition
  div(v-show="show")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
Transition
  MyComp
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
Transition
  component(:is="component")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
Transition
  div(:is="component")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg(height="100", width="100")
  transition
    circle(v-if="show")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg(height="100", width="100")
  transition
    MyComponent
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  template(v-if="show")
    div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  slot
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  div(:key="k")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition(appear)
  div
</template>`
    },
    {
      // https://github.com/vuejs/eslint-plugin-vue/issues/2467
      filename: 'test.vue',
      code: `<template lang="pug">
transition(:appear="foo")
  div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition(:appear="true")
  div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  dialog(v-dialog="show")
</template>`,
      options: [
        {
          additionalDirectives: ['dialog']
        }
      ]
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  div
</template>`,
      errors: [
        {
          messageId: 'expected',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 6
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
Transition
  div
</template>`,
      errors: [
        {
          messageId: 'expected',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 6
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  div
  div
</template>`,
      errors: [
        {
          messageId: 'expected',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 6
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  div(v-for="e in list")
</template>`,
      errors: [
        {
          messageId: 'expected',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg(height="100", width="100")
  transition
    circle
</template>`,
      errors: [
        {
          messageId: 'expected',
          line: 4,
          column: 5,
          endLine: 4,
          endColumn: 11
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  template(v-for="e in list")
    div
</template>`,
      errors: [
        {
          messageId: 'expected',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 30
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition(:appear="false")
  div
</template>`,
      errors: [
        {
          messageId: 'expected',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 6
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition(@appear="isLoaded")
  div
</template>`,
      errors: [
        {
          messageId: 'expected',
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 6
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  dialog(v-dialog="show")
</template>`,
      options: [
        {
          additionalDirectives: []
        }
      ],
      errors: [
        {
          messageId: 'expected',
          data: { allowedDirectives: '`v-if` or `v-show`' },
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 26
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
transition
  div(v-custom="show")
</template>`,
      options: [
        {
          additionalDirectives: ['dialog']
        }
      ],
      errors: [
        {
          messageId: 'expected',
          data: { allowedDirectives: '`v-if`, `v-show` or `v-dialog`' },
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 23
        }
      ]
    }
  ]
})
