// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/require-default-export.test.ts
/**
 * @author ItMaga
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/require-default-export'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('require-default-export', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">| Without script</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <script>
        import { ref } from 'vue';
        
        export default {}
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script setup>
        const foo = 'foo';
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      const component = {};

      export default component;
      </script>
      `
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import {defineComponent} from 'vue';

      export default defineComponent({});
      </script>
      `
    },
    {
      filename: 'test.js',
      code: `
      const foo = 'foo';
      export const bar = 'bar';
      `
    },
    {
      filename: 'test.js',
      code: `
      import {defineComponent} from 'vue';
      defineComponent({});
      `
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `
      <script>
      const foo = 'foo';
      </script>
      `,
      errors: [
        {
          messageId: 'missing',
          line: 4,
          column: 7,
          endLine: 4,
          endColumn: 16
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export const foo = 'foo';
      </script>
      `,
      errors: [
        {
          messageId: 'missing',
          line: 4,
          column: 7,
          endLine: 4,
          endColumn: 16
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      const foo = 'foo';

      export { foo };
      </script>
      `,
      errors: [
        {
          messageId: 'missing',
          line: 6,
          column: 7,
          endLine: 6,
          endColumn: 16
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      export const foo = 'foo';
      export const bar = 'bar';
      </script>
      `,
      errors: [
        {
          messageId: 'missing',
          line: 5,
          column: 7,
          endLine: 5,
          endColumn: 16
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import { defineComponent } from 'vue';

      export const component = defineComponent({});
      </script>
      `,
      errors: [
        {
          messageId: 'mustBeDefaultExport',
          line: 6,
          column: 7,
          endLine: 6,
          endColumn: 16
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <script>
      import Vue from 'vue';

      const component = Vue.component('foo', {});
      </script>
      `,
      errors: [
        {
          messageId: 'mustBeDefaultExport',
          line: 6,
          column: 7,
          endLine: 6,
          endColumn: 16
        }
      ]
    }
  ]
})
