// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/space-infix-ops.test.ts
/**
 * @author Toru Nagashima
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/space-infix-ops'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

const message = (operator: string) => `Operator '${operator}' must be spaced.`

tester.run('space-infix-ops', rule, {
  valid: [
    `<template lang="pug">div(:attr="a + 1")</template>`,
    `<template lang="pug">div(:attr="a ? 1 : 2")</template>`,
    `<template lang="pug">div(:[1+2]="a")</template>`,

    // CSS vars injection
    `
    <style>
    .text {
      padding: v-bind('a + b + "px"')
    }
    </style>`
  ],
  invalid: [
    {
      code: `<template lang="pug">div(:attr="a+1")</template>`,
      output: `<template lang="pug">div(:attr="a + 1")</template>`,
      errors: [
        {
          message: message('+'),
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 35
        }
      ]
    },
    {
      code: `<template lang="pug">div(:attr="a?1 : 2")</template>`,
      output: `<template lang="pug">div(:attr="a ? 1 : 2")</template>`,
      errors: [
        {
          message: message('?'),
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 35
        }
      ]
    },
    {
      code: `<template lang="pug">div(:attr="a ? 1:2")</template>`,
      output: `<template lang="pug">div(:attr="a ? 1 : 2")</template>`,
      errors: [
        {
          message: message(':'),
          line: 1,
          column: 38,
          endLine: 1,
          endColumn: 39
        }
      ]
    },
    {
      code: `<template lang="pug">div(:[1+2]="1+2")</template>`,
      output: `<template lang="pug">div(:[1+2]="1 + 2")</template>`,
      errors: [
        {
          message: message('+'),
          line: 1,
          column: 35,
          endLine: 1,
          endColumn: 36
        }
      ]
    },

    // CSS vars injection
    {
      code: `
      <style>
      .text {
        padding: v-bind('a+b+"px"')
      }
      </style>`,
      output: `
      <style>
      .text {
        padding: v-bind('a + b + "px"')
      }
      </style>`,
      errors: [
        {
          message: message('+'),
          line: 4,
          column: 27,
          endLine: 4,
          endColumn: 28
        },
        {
          message: message('+'),
          line: 4,
          column: 29,
          endLine: 4,
          endColumn: 30
        }
      ]
    }
  ]
})
