// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/space-in-parens.test.ts
/**
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/space-in-parens'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('space-in-parens', rule, {
  valid: [
    `<template lang="pug">button(@click="foo(arg)")</template>`,
    {
      code: `
      <template lang="pug">button(@click="foo( arg )")</template>`,
      options: ['always']
    },
    `
    <template lang="pug">button(:[foo(arg)]="foo(arg)")</template>`,
    {
      code: `
      <template lang="pug">button(:[foo(arg)]="foo( arg )")</template>`,
      options: ['always']
    },
    // CSS vars injection
    `
    <style>
    .text {
      color: v-bind('foo(arg)')
    }
    </style>`
  ],
  invalid: [
    {
      code: `
      <template lang="pug">button(@click="foo( arg )")</template>`,
      output: `
      <template lang="pug">button(@click="foo(arg)")</template>`,
      errors: [
        {
          messageId: 'rejectedOpeningSpace',
          line: 2,
          column: 47,
          endLine: 2,
          endColumn: 48
        },
        {
          messageId: 'rejectedClosingSpace',
          line: 2,
          column: 51,
          endLine: 2,
          endColumn: 52
        }
      ]
    },
    {
      code: `
      <template lang="pug">button(@click="foo(arg)")</template>`,
      output: `
      <template lang="pug">button(@click="foo( arg )")</template>`,
      options: ['always'],
      errors: [
        {
          messageId: 'missingOpeningSpace',
          line: 2,
          column: 46,
          endLine: 2,
          endColumn: 47
        },
        {
          messageId: 'missingClosingSpace',
          line: 2,
          column: 50,
          endLine: 2,
          endColumn: 51
        }
      ]
    },
    {
      code: `
      <template lang="pug">input(:value="( 1 + 2 ) + 3")</template>`,
      output: `
      <template lang="pug">input(:value="(1 + 2) + 3")</template>`,
      errors: [
        {
          messageId: 'rejectedOpeningSpace',
          line: 2,
          column: 43,
          endLine: 2,
          endColumn: 44
        },
        {
          messageId: 'rejectedClosingSpace',
          line: 2,
          column: 49,
          endLine: 2,
          endColumn: 50
        }
      ]
    },
    {
      code: `
      <template lang="pug">input(:value="(1 + 2) + 3")</template>`,
      output: `
      <template lang="pug">input(:value="( 1 + 2 ) + 3")</template>`,
      options: ['always'],
      errors: [
        {
          messageId: 'missingOpeningSpace',
          line: 2,
          column: 42,
          endLine: 2,
          endColumn: 43
        },
        {
          messageId: 'missingClosingSpace',
          line: 2,
          column: 48,
          endLine: 2,
          endColumn: 49
        }
      ]
    },
    {
      code: `
      <template lang="pug">input(:[(1+2)]="( 1 + 2 ) + 3")</template>`,
      output: `
      <template lang="pug">input(:[(1+2)]="(1 + 2) + 3")</template>`,
      errors: [
        {
          messageId: 'rejectedOpeningSpace',
          line: 2,
          column: 45,
          endLine: 2,
          endColumn: 46
        },
        {
          messageId: 'rejectedClosingSpace',
          line: 2,
          column: 51,
          endLine: 2,
          endColumn: 52
        }
      ]
    },
    {
      code: `
      <template lang="pug">input(:[(1+2)]="(1 + 2) + 3")</template>`,
      output: `
      <template lang="pug">input(:[(1+2)]="( 1 + 2 ) + 3")</template>`,
      options: ['always'],
      errors: [
        {
          messageId: 'missingOpeningSpace',
          line: 2,
          column: 44,
          endLine: 2,
          endColumn: 45
        },
        {
          messageId: 'missingClosingSpace',
          line: 2,
          column: 50,
          endLine: 2,
          endColumn: 51
        }
      ]
    },

    // CSS vars injection
    {
      code: `
      <style>
      .text {
        color: v-bind('foo( arg )')
      }
      </style>`,
      output: `
      <style>
      .text {
        color: v-bind('foo(arg)')
      }
      </style>`,
      errors: [
        {
          messageId: 'rejectedOpeningSpace',
          line: 4,
          column: 28,
          endLine: 4,
          endColumn: 29
        },
        {
          messageId: 'rejectedClosingSpace',
          line: 4,
          column: 32,
          endLine: 4,
          endColumn: 33
        }
      ]
    }
  ]
})
