// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/v-if-else-key.test.ts
/**
 * @author Felipe Melendez
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/v-if-else-key'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('v-if-else-key', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  CustomComponent(v-if="some-condition", key="key1")
  CustomComponent(v-else, key="key2")
</template>
        <script>
        export default {
            components: {
                CustomComponent
            }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  CustomComponent(v-if="some-condition")
  CustomComponent
</template>
        <script>
        export default {
            components: {
                CustomComponent
            }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div(v-if="some-condition")
    CustomComponent
  CustomComponent(v-else)
</template>
        <script>
        export default {
            components: {
                CustomComponent
            }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  slot(v-if="some-condition")
  slot(v-else)
</template>
        <script>
        export default {
            components: {
                CustomComponent
            }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div(v-if="someCondition")
  div(v-else-if="otherCondition")
  div(v-else)
</template>
        <script>
        export default {
            components: {
                CustomComponent
            }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div(v-if="foo")
  span(v-else)
</template>
        <script>
        export default {
            components: {
                CustomComponent
            }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div
    ComponentA(v-if="foo")
    ComponentB(v-else-if="bar")
  div
    div
      ComponentA(v-if="foo")
      ComponentB(v-else-if="baz")
    div
      ComponentA(v-if="foo")
      ComponentB(v-else-if="baz")
  div
    ComponentA(v-if="foo")
    ComponentB(v-else)
  div
    div(v-if="foo")
    ComponentB(v-else)
</template>
        <script>
        export default {
          components: {
            ComponentA,
            ComponentB
          }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  div
    CustomComponent(v-if="foo")
    div(v-else)
  CustomComponent(v-if="bar")
</template>
        <script>
        export default {
            components: {
                CustomComponent
            }
        }
        </script>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
tile
  template(v-if="state === 'foo'")
    ComponentA …
    ComponentB …
  ComponentA(v-else-if="state === 'bar'", key="a") …
  ComponentA(v-else-if="state === 'bar'", key="b") …
</template>
        <script>
        export default {
            components: {
                ComponentA,
                ComponentB
            }
        }
        </script>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  OuterComponent(v-if="showOuterComponent")
    InnerComponent(v-if="showInnerComponent1")
    InnerComponent(v-else)
  OuterComponent(v-else)
    InnerComponent(:key="key1")
    InnerComponent(:key="key2")
</template>
        <script>
        export default {
          components: {
            OuterComponent,
            InnerComponent
          }
        }
        </script>`,
      output: `
        <template lang="pug">
div
  OuterComponent(key="outer-component-1", v-if="showOuterComponent")
    InnerComponent(key="inner-component-1", v-if="showInnerComponent1")
    InnerComponent(key="inner-component-2", v-else)
  OuterComponent(key="outer-component-2", v-else)
    InnerComponent(:key="key1")
    InnerComponent(:key="key2")
</template>
        <script>
        export default {
          components: {
            OuterComponent,
            InnerComponent
          }
        }
        </script>`,
      errors: [
        {
          message:
            "Conditionally rendered repeated component 'OuterComponent' expected to have a 'key' attribute.",
          line: 4,
          column: 3,
          endLine: 4,
          endColumn: 44
        },
        {
          message:
            "Conditionally rendered repeated component 'InnerComponent' expected to have a 'key' attribute.",
          line: 5,
          column: 5,
          endLine: 5,
          endColumn: 47
        },
        {
          message:
            "Conditionally rendered repeated component 'InnerComponent' expected to have a 'key' attribute.",
          line: 6,
          column: 5,
          endLine: 6,
          endColumn: 27
        },
        {
          message:
            "Conditionally rendered repeated component 'OuterComponent' expected to have a 'key' attribute.",
          line: 7,
          column: 3,
          endLine: 7,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  OuterComponent(v-if="showOuterComponent")
    InnerComponent(v-if="showInnerComponent1")
      DifferentScopeComponent
    InnerComponent(v-else)
  OuterComponent(v-else)
    InnerComponent
    InnerComponent
  DifferentScopeComponent
</template>
        <script>
        export default {
          components: {
            OuterComponent,
            InnerComponent
          }
        }
        </script>`,
      output: `
        <template lang="pug">
div
  OuterComponent(key="outer-component-1", v-if="showOuterComponent")
    InnerComponent(key="inner-component-1", v-if="showInnerComponent1")
      DifferentScopeComponent
    InnerComponent(key="inner-component-2", v-else)
  OuterComponent(key="outer-component-2", v-else)
    InnerComponent
    InnerComponent
  DifferentScopeComponent
</template>
        <script>
        export default {
          components: {
            OuterComponent,
            InnerComponent
          }
        }
        </script>`,
      errors: [
        {
          message:
            "Conditionally rendered repeated component 'OuterComponent' expected to have a 'key' attribute.",
          line: 4,
          column: 3,
          endLine: 4,
          endColumn: 44
        },
        {
          message:
            "Conditionally rendered repeated component 'InnerComponent' expected to have a 'key' attribute.",
          line: 5,
          column: 5,
          endLine: 5,
          endColumn: 47
        },
        {
          message:
            "Conditionally rendered repeated component 'InnerComponent' expected to have a 'key' attribute.",
          line: 7,
          column: 5,
          endLine: 7,
          endColumn: 27
        },
        {
          message:
            "Conditionally rendered repeated component 'OuterComponent' expected to have a 'key' attribute.",
          line: 8,
          column: 3,
          endLine: 8,
          endColumn: 25
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  OuterComponent(v-if="showOuterComponent")
    InnerComponent(v-if="showInnerComponent1")
    InnerComponent(v-else)
  InnerComponent(v-else)
</template>
        <script>
        export default {
          components: {
            OuterComponent,
            InnerComponent
          }
        }
        </script>`,
      output: `
        <template lang="pug">
div
  OuterComponent(v-if="showOuterComponent")
    InnerComponent(key="inner-component-1", v-if="showInnerComponent1")
    InnerComponent(key="inner-component-2", v-else)
  InnerComponent(v-else)
</template>
        <script>
        export default {
          components: {
            OuterComponent,
            InnerComponent
          }
        }
        </script>`,
      errors: [
        {
          message:
            "Conditionally rendered repeated component 'InnerComponent' expected to have a 'key' attribute.",
          line: 5,
          column: 5,
          endLine: 5,
          endColumn: 47
        },
        {
          message:
            "Conditionally rendered repeated component 'InnerComponent' expected to have a 'key' attribute.",
          line: 6,
          column: 5,
          endLine: 6,
          endColumn: 27
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  ComponentA(v-if="foo")
  ComponentA(v-else-if="bar")
  ComponentB(v-else)
</template>
        <script>
        export default {
          components: {
            ComponentA,
            ComponentB
          }
        }
        </script>`,
      output: `
        <template lang="pug">
div
  ComponentA(key="component-a-1", v-if="foo")
  ComponentA(key="component-a-2", v-else-if="bar")
  ComponentB(v-else)
</template>
        <script>
        export default {
          components: {
            ComponentA,
            ComponentB
          }
        }
        </script>`,
      errors: [
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 4,
          column: 3,
          endLine: 4,
          endColumn: 25
        },
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 5,
          column: 3,
          endLine: 5,
          endColumn: 30
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  ComponentA(v-if="foo")
  ComponentB(v-else-if="bar")
  ComponentA(v-else)
</template>
        <script>
        export default {
          components: {
            ComponentA,
            ComponentB
          }
        }
        </script>`,
      output: `
        <template lang="pug">
div
  ComponentA(key="component-a-1", v-if="foo")
  ComponentB(v-else-if="bar")
  ComponentA(key="component-a-2", v-else)
</template>
        <script>
        export default {
          components: {
            ComponentA,
            ComponentB
          }
        }
        </script>`,
      errors: [
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 4,
          column: 3,
          endLine: 4,
          endColumn: 25
        },
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 6,
          column: 3,
          endLine: 6,
          endColumn: 21
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div
  ComponentA(v-if="foo")
  ComponentA(v-else)
  ComponentA(v-if="bar")
  ComponentA(v-else-if="baz")
  ComponentA(v-else)
</template>
        <script>
        export default {
          components: {
            ComponentA
          }
        }
        </script>`,
      output: `
        <template lang="pug">
div
  ComponentA(key="component-a-1", v-if="foo")
  ComponentA(key="component-a-2", v-else)
  ComponentA(key="component-a-3", v-if="bar")
  ComponentA(key="component-a-4", v-else-if="baz")
  ComponentA(key="component-a-5", v-else)
</template>
        <script>
        export default {
          components: {
            ComponentA
          }
        }
        </script>`,
      errors: [
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 4,
          column: 3,
          endLine: 4,
          endColumn: 25
        },
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 5,
          column: 3,
          endLine: 5,
          endColumn: 21
        },
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 6,
          column: 3,
          endLine: 6,
          endColumn: 25
        },
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 7,
          column: 3,
          endLine: 7,
          endColumn: 30
        },
        {
          message:
            "Conditionally rendered repeated component 'ComponentA' expected to have a 'key' attribute.",
          line: 8,
          column: 3,
          endLine: 8,
          endColumn: 21
        }
      ]
    }
  ]
})
