// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/v-on-event-hyphenation.test.ts
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/v-on-event-hyphenation'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2019,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('v-on-event-hyphenation', rule, {
  valid: [
    `
    <template lang="pug">VueComponent(@custom-event="onEvent")</template>`,
    `
    <template lang="pug">VueComponent(:customEvent="onEvent")</template>`,
    `
    <template lang="pug">VueComponent(v-on="events")</template>`,
    `
    <template lang="pug">div(v-on:unknownEvent="onEvent")</template>`,
    {
      code: `
      <template lang="pug">VueComponent(v-on:customEvent="events")</template>`,
      options: ['never']
    },
    {
      code: `
      <template lang="pug">VueComponent(v-on:customEvent="events")</template>`,
      options: ['never', { ignore: ['custom'] }]
    },
    {
      code: `
      <template lang="pug">VueComponent(v-on:custom-event="events")</template>`,
      options: ['never', { ignore: ['custom-event'] }]
    },
    {
      code: `
      <template lang="pug">
VueComponent(v-on:custom-event="events")
custom-component(v-on:custom-event="events")
</template>`,
      options: ['never', { ignoreTags: ['/^Vue/', 'custom-component'] }]
    },
    {
      code: `
      <template lang="pug">
VueComponent(v-on:customEvent="events")
custom-component(v-on:customEvent="events")
</template>`,
      options: ['always', { ignoreTags: ['/^Vue/', 'custom-component'] }]
    }
  ],
  invalid: [
    {
      code: `
      <template lang="pug">VueComponent(@customEvent="onEvent")</template>`,
      output: null,
      errors: [
        {
          message: "v-on event '@customEvent' must be hyphenated.",
          line: 2,
          column: 41,
          endLine: 2,
          endColumn: 63
        }
      ]
    },
    {
      code: `
      <template lang="pug">VueComponent(@customEvent="onEvent")</template>`,
      output: `
      <template lang="pug">VueComponent(@custom-event="onEvent")</template>`,
      options: ['always', { autofix: true }],
      errors: [
        {
          message: "v-on event '@customEvent' must be hyphenated.",
          line: 2,
          column: 41,
          endLine: 2,
          endColumn: 63
        }
      ]
    },
    {
      code: `
      <template lang="pug">VueComponent(v-on:custom-event="events")</template>`,
      output: `
      <template lang="pug">VueComponent(v-on:customEvent="events")</template>`,
      options: ['never', { autofix: true }],
      errors: [
        {
          message: "v-on event 'v-on:custom-event' can't be hyphenated.",
          line: 2,
          column: 41,
          endLine: 2,
          endColumn: 67
        }
      ]
    },
    {
      code: `
      <template lang="pug">
VueComponent(@update:modelValue="foo")
VueComponent(@update:model-value="foo")
</template>`,
      output: `
      <template lang="pug">
VueComponent(@update:model-value="foo")
VueComponent(@update:model-value="foo")
</template>`,
      options: ['always', { autofix: true }],
      errors: [
        {
          message: "v-on event '@update:modelValue' must be hyphenated.",
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 38
        }
      ]
    },
    {
      code: `
      <template lang="pug">
VueComponent(@update:modelValue="foo")
VueComponent(@update:model-value="foo")
</template>`,
      output: `
      <template lang="pug">
VueComponent(@update:modelValue="foo")
VueComponent(@update:modelValue="foo")
</template>`,
      options: ['never', { autofix: true }],
      errors: [
        {
          message: "v-on event '@update:model-value' can't be hyphenated.",
          line: 4,
          column: 14,
          endLine: 4,
          endColumn: 39
        }
      ]
    },
    {
      code: `
      <template lang="pug">
VueComponent(@upDate:modelValue="foo")
VueComponent(@up-date:modelValue="foo")
VueComponent(@upDate:model-value="foo")
VueComponent(@up-date:model-value="foo")
</template>`,
      output: `
      <template lang="pug">
VueComponent(@up-date:model-value="foo")
VueComponent(@up-date:model-value="foo")
VueComponent(@up-date:model-value="foo")
VueComponent(@up-date:model-value="foo")
</template>`,
      options: ['always', { autofix: true }],
      errors: [
        {
          message: "v-on event '@upDate:modelValue' must be hyphenated.",
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 38
        },
        {
          message: "v-on event '@up-date:modelValue' must be hyphenated.",
          line: 4,
          column: 14,
          endLine: 4,
          endColumn: 39
        },
        {
          message: "v-on event '@upDate:model-value' must be hyphenated.",
          line: 5,
          column: 14,
          endLine: 5,
          endColumn: 39
        }
      ]
    },
    {
      code: `
      <template lang="pug">
VueComponent(@upDate:modelValue="foo")
VueComponent(@up-date:modelValue="foo")
VueComponent(@upDate:model-value="foo")
VueComponent(@up-date:model-value="foo")
</template>`,
      output: `
      <template lang="pug">
VueComponent(@upDate:modelValue="foo")
VueComponent(@upDate:modelValue="foo")
VueComponent(@upDate:modelValue="foo")
VueComponent(@upDate:modelValue="foo")
</template>`,
      options: ['never', { autofix: true }],
      errors: [
        {
          message: "v-on event '@up-date:modelValue' can't be hyphenated.",
          line: 4,
          column: 14,
          endLine: 4,
          endColumn: 39
        },
        {
          message: "v-on event '@upDate:model-value' can't be hyphenated.",
          line: 5,
          column: 14,
          endLine: 5,
          endColumn: 39
        },
        {
          message: "v-on event '@up-date:model-value' can't be hyphenated.",
          line: 6,
          column: 14,
          endLine: 6,
          endColumn: 40
        }
      ]
    },
    {
      code: `
      <template lang="pug">
VueComponent(v-on:custom-event="events")
CustomComponent(v-on:custom-event="events")
</template>`,
      output: `
      <template lang="pug">
VueComponent(v-on:customEvent="events")
CustomComponent(v-on:custom-event="events")
</template>`,
      options: ['never', { autofix: true, ignoreTags: ['CustomComponent'] }],
      errors: [
        {
          message: "v-on event 'v-on:custom-event' can't be hyphenated.",
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 40
        }
      ]
    },
    {
      code: `
      <template lang="pug">
VueComponent(v-on:customEvent="events")
CustomComponent(v-on:customEvent="events")
</template>`,
      output: `
      <template lang="pug">
VueComponent(v-on:custom-event="events")
CustomComponent(v-on:customEvent="events")
</template>`,
      options: ['always', { autofix: true, ignoreTags: ['CustomComponent'] }],
      errors: [
        {
          message: "v-on event 'v-on:customEvent' must be hyphenated.",
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 39
        }
      ]
    }
  ]
})
