// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/v-slot-style.test.ts
/**
 * @author Toru Nagashima
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/v-slot-style'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('v-slot-style', rule, {
  valid: [
    `
      <template lang="pug">
my-component(v-slot="data")
  template(#default)
  template(#foo)
</template>`,
    {
      code: `
        <template lang="pug">
template
  my-component(#default="data")
    template(#default)
    template(#foo)
</template>`,
      options: ['shorthand']
    },
    {
      code: `
        <template lang="pug">
template
  my-component(v-slot:default="data")
    template(v-slot:default)
    template(v-slot:foo)
</template>`,
      options: ['longform']
    },

    {
      code: `
        <template lang="pug">
template
  my-component(#default="data")
    template(#default)
    template(#foo)
</template>`,
      options: [{ atComponent: 'shorthand' }]
    },
    {
      code: `
        <template lang="pug">
template
  my-component(v-slot:default="data")
    template(#default)
    template(#foo)
</template>`,
      options: [{ atComponent: 'longform' }]
    },
    {
      code: `
        <template lang="pug">
template
  my-component(v-slot="data")
    template(#default)
    template(#foo)
</template>`,
      options: [{ atComponent: 'v-slot' }]
    },

    {
      code: `
        <template lang="pug">
template
  my-component(v-slot="data")
    template(#default)
    template(#foo)
</template>`,
      options: [{ default: 'shorthand' }]
    },
    {
      code: `
        <template lang="pug">
template
  my-component(v-slot="data")
    template(v-slot:default)
    template(#foo)
</template>`,
      options: [{ default: 'longform' }]
    },
    {
      code: `
        <template lang="pug">
template
  my-component(v-slot="data")
    template(v-slot)
    template(#foo)
</template>`,
      options: [{ default: 'v-slot' }]
    },

    {
      code: `
        <template lang="pug">
template
  my-component(v-slot="data")
    template(#default)
    template(#foo)
</template>`,
      options: [{ named: 'shorthand' }]
    },
    {
      code: `
        <template lang="pug">
template
  my-component(v-slot="data")
    template(#default)
    template(v-slot:foo)
</template>`,
      options: [{ named: 'longform' }]
    },
    {
      code: `
        <template lang="pug">
template
  my-component
    template(v-slot:[default])
</template>`,
      options: [{ named: 'longform' }]
    }
  ],

  invalid: [
    {
      code: `
        <template lang="pug">my-component(#default="data")</template>`,
      output: `
        <template lang="pug">my-component(v-slot="data")</template>`,
      errors: [
        {
          messageId: 'expectedVSlot',
          data: { actual: '#default', argument: 'default' },
          line: 2,
          column: 43,
          endLine: 2,
          endColumn: 58
        }
      ]
    },
    {
      code: `
        <template lang="pug">my-component(v-slot:default="data")</template>`,
      output: `
        <template lang="pug">my-component(v-slot="data")</template>`,
      errors: [
        {
          messageId: 'expectedVSlot',
          data: { actual: 'v-slot:default', argument: 'default' },
          line: 2,
          column: 43,
          endLine: 2,
          endColumn: 64
        }
      ]
    },
    {
      code: `
        <template lang="pug">my-component(v-slot:default="data")</template>`,
      output: `
        <template lang="pug">my-component(#default="data")</template>`,
      options: [{ atComponent: 'shorthand' }],
      errors: [
        {
          messageId: 'expectedShorthand',
          data: { actual: 'v-slot:default', argument: 'default' },
          line: 2,
          column: 43,
          endLine: 2,
          endColumn: 64
        }
      ]
    },
    {
      code: `
        <template lang="pug">my-component(v-slot="data")</template>`,
      output: `
        <template lang="pug">my-component(#default="data")</template>`,
      options: [{ atComponent: 'shorthand' }],
      errors: [
        {
          messageId: 'expectedShorthand',
          data: { actual: 'v-slot', argument: 'default' },
          line: 2,
          column: 43,
          endLine: 2,
          endColumn: 56
        }
      ]
    },
    {
      code: `
        <template lang="pug">my-component(#default="data")</template>`,
      output: `
        <template lang="pug">my-component(v-slot:default="data")</template>`,
      options: [{ atComponent: 'longform' }],
      errors: [
        {
          messageId: 'expectedLongform',
          data: { actual: '#default', argument: 'default' },
          line: 2,
          column: 43,
          endLine: 2,
          endColumn: 58
        }
      ]
    },
    {
      code: `
        <template lang="pug">my-component(v-slot="data")</template>`,
      output: `
        <template lang="pug">my-component(v-slot:default="data")</template>`,
      options: [{ atComponent: 'longform' }],
      errors: [
        {
          messageId: 'expectedLongform',
          data: { actual: 'v-slot', argument: 'default' },
          line: 2,
          column: 43,
          endLine: 2,
          endColumn: 56
        }
      ]
    },

    {
      code: `
        <template lang="pug">
my-component
  template(v-slot)
</template>`,
      output: `
        <template lang="pug">
my-component
  template(#default)
</template>`,
      errors: [
        {
          messageId: 'expectedShorthand',
          data: { actual: 'v-slot', argument: 'default' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 18
        }
      ]
    },
    {
      code: `
        <template lang="pug">
my-component
  template(v-slot:default)
</template>`,
      output: `
        <template lang="pug">
my-component
  template(#default)
</template>`,
      errors: [
        {
          messageId: 'expectedShorthand',
          data: { actual: 'v-slot:default', argument: 'default' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 26
        }
      ]
    },
    {
      code: `
        <template lang="pug">
my-component
  template(#default)
</template>`,
      output: `
        <template lang="pug">
my-component
  template(v-slot:default)
</template>`,
      options: [{ default: 'longform' }],
      errors: [
        {
          messageId: 'expectedLongform',
          data: { actual: '#default', argument: 'default' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 20
        }
      ]
    },
    {
      code: `
        <template lang="pug">
my-component
  template(v-slot)
</template>`,
      output: `
        <template lang="pug">
my-component
  template(v-slot:default)
</template>`,
      options: [{ default: 'longform' }],
      errors: [
        {
          messageId: 'expectedLongform',
          data: { actual: 'v-slot', argument: 'default' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 18
        }
      ]
    },
    {
      code: `
        <template lang="pug">
my-component
  template(#default)
</template>`,
      output: `
        <template lang="pug">
my-component
  template(v-slot)
</template>`,
      options: [{ default: 'v-slot' }],
      errors: [
        {
          messageId: 'expectedVSlot',
          data: { actual: '#default', argument: 'default' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 20
        }
      ]
    },
    {
      code: `
        <template lang="pug">
my-component
  template(v-slot:default)
</template>`,
      output: `
        <template lang="pug">
my-component
  template(v-slot)
</template>`,
      options: [{ default: 'v-slot' }],
      errors: [
        {
          messageId: 'expectedVSlot',
          data: { actual: 'v-slot:default', argument: 'default' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 26
        }
      ]
    },

    {
      code: `
        <template lang="pug">
my-component
  template(v-slot:foo)
</template>`,
      output: `
        <template lang="pug">
my-component
  template(#foo)
</template>`,
      errors: [
        {
          messageId: 'expectedShorthand',
          data: { actual: 'v-slot:foo', argument: 'foo' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 22
        }
      ]
    },
    {
      code: `
        <template lang="pug">
my-component
  template(#foo)
</template>`,
      output: `
        <template lang="pug">
my-component
  template(v-slot:foo)
</template>`,
      options: [{ named: 'longform' }],
      errors: [
        {
          messageId: 'expectedLongform',
          data: { actual: '#foo', argument: 'foo' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 16
        }
      ]
    },

    {
      code: `
        <template lang="pug">
my-component
  template(v-slot:[foo])
</template>`,
      output: `
        <template lang="pug">
my-component
  template(#[foo])
</template>`,
      errors: [
        {
          messageId: 'expectedShorthand',
          data: { actual: 'v-slot:[foo]', argument: '[foo]' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 24
        }
      ]
    },
    {
      code: `
        <template lang="pug">
my-component
  template(#[foo])
</template>`,
      output: `
        <template lang="pug">
my-component
  template(v-slot:[foo])
</template>`,
      options: [{ named: 'longform' }],
      errors: [
        {
          messageId: 'expectedLongform',
          data: { actual: '#[foo]', argument: '[foo]' },
          line: 4,
          column: 12,
          endLine: 4,
          endColumn: 18
        }
      ]
    }
  ]
})
