// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/valid-v-cloak.test.ts
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/valid-v-cloak'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('valid-v-cloak', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-cloak)</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-cloak:aaa)</template>`,
      errors: [
        {
          message: "'v-cloak' directives require no argument.",
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 37
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-cloak.aaa)</template>`,
      errors: [
        {
          message: "'v-cloak' directives require no modifier.",
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 37
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-cloak="aaa")</template>`,
      errors: [
        {
          message: "'v-cloak' directives require no attribute value.",
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 39
        }
      ]
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">div(v-cloak=".")</template>`,
      errors: [
        {
          message: "'v-cloak' directives require no attribute value.",
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 37
        }
      ]
    },
    // comment value
    {
      filename: 'comment-value.vue',
      code: `<template lang="pug">div(v-cloak="/**/")</template>`,
      errors: [
        {
          message: "'v-cloak' directives require no attribute value.",
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 40
        }
      ]
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">div(v-cloak="")</template>`,
      errors: [
        {
          message: "'v-cloak' directives require no attribute value.",
          line: 1,
          column: 34,
          endLine: 1,
          endColumn: 36
        }
      ]
    }
  ]
})
