// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/valid-v-bind-sync.test.ts
/**
 * @author Yosuke Ota
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/valid-v-bind-sync'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2020,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('valid-v-bind-sync', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind:foo.sync="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="foo.bar")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind.sync="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg
  MyComponent(:foo.sync="foo")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="this.foo().bar")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg
  MyComponent(:foo.sync="this.foo().bar")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="x.foo")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x - 1]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[\`${x}\`]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[\`prefix_${x}\`]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x ? x : '_']")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x || '_']")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[x()]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[/r/.match(x) ? 0 : 1]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[typeof x]")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
    MyComponent(:foo.sync="foo[tag\`${x}\`]")
</template>`
    },
    // not .sync
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo="a + b")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind:foo="a + b")</template>`
    },
    // does not report
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync)</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind:foo.sync)</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync.unknown="foo")</template>`
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">MyComponent(:foo.sync=".")</template>`
    },
    // comment value (parsing error)
    {
      filename: 'comment-value.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="/**/")</template>`
    },
    // empty value (valid-v-bind)
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">MyComponent(:foo.sync=)</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
table
  tr(is="my-row", :some-prop.sync="somePropValue", :some-other-prop.sync="someOtherPropValue")
    td
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
table
  tr(:is="my-row", :some-prop.sync="somePropValue", :some-other-prop.sync="someOtherPropValue")
    td
</template>`
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
table
  tr(v-bind:is="myRow", :some-prop.sync="somePropValue", :some-other-prop.sync="someOtherPropValue")
    td
</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">MyComponent(:foo.sync="a + b")</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers require the attribute value which is valid as LHS.",
          line: 2,
          column: 53,
          endLine: 2,
          endColumn: 58
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">MyComponent(v-bind:foo.sync="a + b")</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers require the attribute value which is valid as LHS.",
          line: 2,
          column: 59,
          endLine: 2,
          endColumn: 64
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">input(:foo.sync="foo")</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers aren't supported on <input> non Vue-components.",
          line: 2,
          column: 36,
          endLine: 2,
          endColumn: 51
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">MyComponent(:foo.sync="foo()")</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers require the attribute value which is valid as LHS.",
          line: 2,
          column: 53,
          endLine: 2,
          endColumn: 58
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">MyComponent(:foo.sync="this.foo()")</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers require the attribute value which is valid as LHS.",
          line: 2,
          column: 53,
          endLine: 2,
          endColumn: 63
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">input(v-bind:foo.sync="foo")</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers aren't supported on <input> non Vue-components.",
          line: 2,
          column: 36,
          endLine: 2,
          endColumn: 57
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div(v-for="x in list")
  MyComponent(:foo.sync="x")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers cannot update the iteration variable 'x' itself.",
          line: 4,
          column: 26,
          endLine: 4,
          endColumn: 27
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div(v-for="e in list")
  MyComponent(v-bind:foo.sync="e")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers cannot update the iteration variable 'e' itself.",
          line: 4,
          column: 32,
          endLine: 4,
          endColumn: 33
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div(v-for="e1 in list1")
  div
    div
      div(v-for="e2 in list2")
        MyComponent(v-bind:foo.sync="e1")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers cannot update the iteration variable 'e1' itself.",
          line: 7,
          column: 38,
          endLine: 7,
          endColumn: 40
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
div(v-for="(e, index) in list")
  MyComponent(v-bind:foo.sync="index")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers cannot update the iteration variable 'index' itself.",
          line: 4,
          column: 32,
          endLine: 4,
          endColumn: 37
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">div(:foo.sync="foo")</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers aren't supported on <div> non Vue-components.",
          line: 2,
          column: 34,
          endLine: 2,
          endColumn: 49
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(v-bind.sync="foo()")</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers require the attribute value which is valid as LHS.",
          line: 1,
          column: 47,
          endLine: 1,
          endColumn: 52
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
svg
  MyComponent(:foo.sync="foo()")
</template>`,
      errors: [
        {
          message:
            "'.sync' modifiers require the attribute value which is valid as LHS.",
          line: 3,
          column: 26,
          endLine: 3,
          endColumn: 31
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="foo?.bar")</template>`,
      errors: [
        {
          message:
            "Optional chaining cannot appear in 'v-bind' with '.sync' modifiers.",
          line: 1,
          column: 45,
          endLine: 1,
          endColumn: 53
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="foo?.bar.baz")</template>`,
      errors: [
        {
          message:
            "Optional chaining cannot appear in 'v-bind' with '.sync' modifiers.",
          line: 1,
          column: 45,
          endLine: 1,
          endColumn: 57
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="(a?.b)?.c")</template>`,
      errors: [
        {
          message:
            "Optional chaining cannot appear in 'v-bind' with '.sync' modifiers.",
          line: 1,
          column: 45,
          endLine: 1,
          endColumn: 54
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="(a?.b).c")</template>`,
      errors: [
        {
          message:
            "'.sync' modifier has potential null object property access.",
          line: 1,
          column: 45,
          endLine: 1,
          endColumn: 53
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="(null).foo")</template>`,
      errors: [
        {
          message:
            "'.sync' modifier has potential null object property access.",
          line: 1,
          column: 45,
          endLine: 1,
          endColumn: 55
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">MyComponent(:foo.sync="(a?.b).c.d")</template>`,
      errors: [
        {
          message:
            "'.sync' modifier has potential null object property access.",
          line: 1,
          column: 45,
          endLine: 1,
          endColumn: 55
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Element is missing end tag.<template><tr v-on:is="myRow" :some-prop.sync="somePropValue"></template>`,
      errors: [
        {
          message:
            "'.sync' modifiers aren't supported on <tr> non Vue-components.",
          line: 1,
          column: 80,
          endLine: 1,
          endColumn: 111
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Element is missing end tag.<template><tr v-bind="myRow" :some-prop.sync="somePropValue"></template>`,
      errors: [
        {
          message:
            "'.sync' modifiers aren't supported on <tr> non Vue-components.",
          line: 1,
          column: 79,
          endLine: 1,
          endColumn: 110
        }
      ]
    }
  ]
})
