// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/valid-v-on.test.ts
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/valid-v-on'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: { parser: vueEslintParser, ecmaVersion: 2015 }
})

tester.run('valid-v-on', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-on:click="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@click="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@click.prevent.ctrl.left="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.27="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.enter="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.arrow-down="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.esc="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.a="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.b="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.a.b.c="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Invalid end tag.<template><el-from @submit.native.prevent></el-form></template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-on:click.prevent)</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-on:click.native.stop)</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-on="\$listeners")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-on="{a, b, c: d}")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.bar="foo")</template>`,
      options: [{ modifiers: ['bar'] }]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-on:keydown.bar.aaa="foo")</template>`,
      options: [{ modifiers: ['bar', 'aaa'] }]
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">MyComponent(v-on:keydown=".")</template>`
    },
    // comment value (valid)
    {
      filename: 'comment-value.vue',
      code: `<template lang="pug">MyComponent(v-on:keydown="/**/")</template>`
    },
    {
      filename: 'comment-value.vue',
      code: `<template lang="pug">MyComponent(v-on:keydown.stop="/**/")</template>`
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">MyComponent(v-on:keydown.stop=)</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-on:click.aaa="foo")</template>`,
      errors: [
        {
          message: "'v-on' directives don't support the modifier 'aaa'.",
          line: 1,
          column: 27,
          endLine: 1,
          endColumn: 30
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-on:click)</template>`,
      errors: [
        {
          message:
            "'v-on' directives require a value or verb modifier (like 'stop' or 'prevent').",
          line: 1,
          column: 16,
          endLine: 1,
          endColumn: 26
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@click)</template>`,
      errors: [
        {
          message:
            "'v-on' directives require a value or verb modifier (like 'stop' or 'prevent').",
          line: 1,
          column: 16,
          endLine: 1,
          endColumn: 22
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.bar.aaa="foo")</template>`,
      options: [{ modifiers: ['bar'] }],
      errors: [
        {
          message: "'v-on' directives don't support the modifier 'aaa'.",
          line: 1,
          column: 29,
          endLine: 1,
          endColumn: 32
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@keydown.bar.aaa="foo")</template>`,
      options: [{ modifiers: ['aaa'] }],
      errors: [
        {
          message: "'v-on' directives don't support the modifier 'bar'.",
          line: 1,
          column: 25,
          endLine: 1,
          endColumn: 28
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@click="const")</template>`,
      errors: [
        {
          message: 'Avoid using JavaScript keyword as "v-on" value: "const".',
          line: 1,
          column: 23,
          endLine: 1,
          endColumn: 30
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(@click="delete")</template>`,
      errors: [
        {
          message: 'Avoid using JavaScript keyword as "v-on" value: "delete".',
          line: 1,
          column: 23,
          endLine: 1,
          endColumn: 31
        }
      ]
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">MyComponent(v-on:keydown=)</template>`,
      errors: [
        {
          message:
            "'v-on' directives require a value or verb modifier (like 'stop' or 'prevent').",
          line: 1,
          column: 24,
          endLine: 1,
          endColumn: 39
        }
      ]
    }
  ]
})
