// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/valid-v-if.test.ts
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/valid-v-if'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('valid-v-if', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-if="foo")
</template>`
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">div(v-if=".")</template>`
    },
    // comment value (parsing error)
    {
      filename: 'comment-value.vue',
      code: `<template lang="pug">div(v-if="/**/")</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-if="foo", v-else)
</template>`,
      errors: [
        {
          message:
            "'v-if' and 'v-else' directives can't exist on the same element. You may want 'v-else-if' directives.",
          line: 3,
          column: 7,
          endLine: 3,
          endColumn: 17
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-if="foo", v-else-if="bar")
</template>`,
      errors: [
        {
          message:
            "'v-if' and 'v-else-if' directives can't exist on the same element.",
          line: 3,
          column: 7,
          endLine: 3,
          endColumn: 17
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-if:aaa="foo")
</template>`,
      errors: [
        {
          message: "'v-if' directives require no argument.",
          line: 3,
          column: 12,
          endLine: 3,
          endColumn: 15
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-if.aaa="foo")
</template>`,
      errors: [
        {
          message: "'v-if' directives require no modifier.",
          line: 3,
          column: 12,
          endLine: 3,
          endColumn: 15
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-if)
</template>`,
      errors: [
        {
          message: "'v-if' directives require that attribute value.",
          line: 3,
          column: 7,
          endLine: 3,
          endColumn: 11
        }
      ]
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">
div
  div(v-if="")
</template>`,
      errors: [
        {
          message: "'v-if' directives require that attribute value.",
          line: 3,
          column: 7,
          endLine: 3,
          endColumn: 14
        }
      ]
    }
  ]
})
