// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/valid-v-memo.test.ts
/**
 * @author Yosuke Ota <https://github.com/ota-meshi>
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/valid-v-memo'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2021,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('valid-v-memo', rule, {
  valid: [
    {
      filename: 'test.js',
      code: 'test'
    },
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-memo="[x]")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-memo="x")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-memo="x?y:z")</template>`
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">div(v-memo=".")</template>`
    },
    // comment value (parsing error)
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">div(v-memo="/**/")</template>`
    },
    // v-for
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-for="i in items", v-memo="[x]")</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-memo:aaa="x")</template>`,
      errors: [
        {
          message: "'v-memo' directives require no argument.",
          line: 1,
          column: 33,
          endLine: 1,
          endColumn: 36
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-memo.aaa="x")</template>`,
      errors: [
        {
          message: "'v-memo' directives require no modifier.",
          line: 1,
          column: 33,
          endLine: 1,
          endColumn: 36
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-memo)</template>`,
      errors: [
        {
          message: "'v-memo' directives require that attribute value.",
          line: 1,
          column: 26,
          endLine: 1,
          endColumn: 32
        }
      ]
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">div(v-memo="")</template>`,
      errors: [
        {
          message: "'v-memo' directives require that attribute value.",
          line: 1,
          column: 26,
          endLine: 1,
          endColumn: 35
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
      <template lang="pug">
div(v-memo="{x}")
div(v-memo="a ? {b}: c+d")
div(v-memo="(a,{b},c(),d+1)")
div(v-memo="()=>42")
div(v-memo="a=42")
</template>`,
      errors: [
        {
          message:
            "'v-memo' directives require the attribute value to be an array.",
          line: 3,
          column: 13,
          endLine: 3,
          endColumn: 16
        },
        {
          message:
            "'v-memo' directives require the attribute value to be an array.",
          line: 4,
          column: 17,
          endLine: 4,
          endColumn: 20
        },
        {
          message:
            "'v-memo' directives require the attribute value to be an array.",
          line: 4,
          column: 22,
          endLine: 4,
          endColumn: 25
        },
        {
          message:
            "'v-memo' directives require the attribute value to be an array.",
          line: 5,
          column: 24,
          endLine: 5,
          endColumn: 27
        },
        {
          message:
            "'v-memo' directives require the attribute value to be an array.",
          line: 6,
          column: 13,
          endLine: 6,
          endColumn: 19
        },
        {
          message:
            "'v-memo' directives require the attribute value to be an array.",
          line: 7,
          column: 15,
          endLine: 7,
          endColumn: 17
        }
      ]
    },
    // v-for
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div(v-for="i in items")
  div(v-memo="[x]")
</template>`,
      errors: [
        {
          message: "'v-memo' directive does not work inside 'v-for'.",
          line: 3,
          column: 7,
          endLine: 3,
          endColumn: 13
        }
      ]
    }
  ]
})
