// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/valid-v-for.test.ts
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/valid-v-for'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('valid-v-for', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x of list")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(x, i, k) in list")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(x, i, k) of list")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="({id, name}, i, k) of list")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="([id, name], i, k) of list")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  your-component(v-for="x in list", :key="x.id")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(is="your-component", v-for="x in list", :key="x.id")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(:is="your-component", v-for="x in list", :key="x.id")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list")
    custom-component(:key="x")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list")
    div(:key="x")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list")
    div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
template(v-for="x of list")
  slot(name="item")
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
template(v-for="x of list") foo
  div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x of list")
    div(v-for="foo of x", :key="foo")
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="x in xs")
  template(v-for="y in x.ys")
    li(v-for="z in y.zs", :key="z.id") 123
</template>`
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="x in xs")
  template(v-for="y in ys")
    li(v-for="z in zs", :key="x.id + y.id + z.id") 123
</template>`
    },
    // key on <template> : In Vue.js 3.x, you can place key on <template>.
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", v-bind:key="x")
    div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", v-bind:key="x")
    MyComp
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key="x")
    div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key="x")
    MyComp
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key="x.id")
    div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key="x.id")
    MyComp
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="(x, i) in list", :key="i")
    div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="(x, i) in list", :key="i")
    MyComp
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x in list", :key="x")
    custom-component
</template>`
    },
    // key on <slot> : In Vue.js 3.x, you can place key on <slot>.
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  slot(v-for="x in list", :key="x")
    div
</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  slot(v-for="x in list", :key="x")
    MyComp
</template>`
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">div(v-for=".")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="xin list")
    div
</template>`
    },
    // comment value (parsing error)
    {
      filename: 'comment-value.vue',
      code: `<template lang="pug">div(v-for="/**/")</template>`
    },
    // allowEmptyAlias option
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(,a) in list")
</template>`,
      options: [{ allowEmptyAlias: true }]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(,a,b) in list")
</template>`,
      options: [{ allowEmptyAlias: true }]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(a,,b) in list")
</template>`,
      options: [{ allowEmptyAlias: true }]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(a,b,,) in list")
</template>`,
      options: [{ allowEmptyAlias: true }]
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for:aaa="x in list")
</template>`,
      errors: [
        {
          message: "'v-for' directives require no argument.",
          line: 3,
          column: 13,
          endLine: 3,
          endColumn: 16
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for.aaa="x in list")
</template>`,
      errors: [
        {
          message: "'v-for' directives require no modifier.",
          line: 3,
          column: 13,
          endLine: 3,
          endColumn: 16
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for)
</template>`,
      errors: [
        {
          message: "'v-for' directives require that attribute value.",
          line: 3,
          column: 7,
          endLine: 3,
          endColumn: 12
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(,a,b) in list")
</template>`,
      errors: [
        {
          message: 'Invalid empty alias.',
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 28
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(a,,b) in list")
</template>`,
      errors: [
        {
          message: 'Invalid empty alias.',
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 28
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(a,b,,) in list")
</template>`,
      errors: [
        {
          message: 'Invalid empty alias.',
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 29
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(a,{b,c}) in list")
</template>`,
      errors: [
        {
          message: "Invalid alias '{b,c}'.",
          line: 3,
          column: 17,
          endLine: 3,
          endColumn: 22
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(a,b,{c,d}) in list")
</template>`,
      errors: [
        {
          message: "Invalid alias '{c,d}'.",
          line: 3,
          column: 19,
          endLine: 3,
          endColumn: 24
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  your-component(v-for="x in list")
</template>`,
      errors: [
        {
          message:
            "Custom elements in iteration require 'v-bind:key' directives.",
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 36
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(is="your-component", v-for="x in list")
</template>`,
      errors: [
        {
          message:
            "Custom elements in iteration require 'v-bind:key' directives.",
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 46
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(:is="your-component", v-for="x in list")
</template>`,
      errors: [
        {
          message:
            "Custom elements in iteration require 'v-bind:key' directives.",
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 47
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-bind:is="your-component", v-for="x in list")
</template>`,
      errors: [
        {
          message:
            "Custom elements in iteration require 'v-bind:key' directives.",
          line: 3,
          column: 3,
          endLine: 3,
          endColumn: 53
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list", :key="100")
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 3,
          column: 26,
          endLine: 3,
          endColumn: 36
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  custom-component(v-for="x in list", :key="100")
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 3,
          column: 39,
          endLine: 3,
          endColumn: 49
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="x in list", :key="foo")
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 3,
          column: 26,
          endLine: 3,
          endColumn: 36
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  custom-component(v-for="x in list", :key="foo")
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 3,
          column: 39,
          endLine: 3,
          endColumn: 49
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(item, index) in suggestions", :key)
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 3,
          column: 45,
          endLine: 3,
          endColumn: 49
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  template(v-for="x of list")
    div(v-for="foo of y", :key="foo")
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 4,
          column: 27,
          endLine: 4,
          endColumn: 37
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="x in xs")
  template(v-for="y in a.ys")
    li(v-for="z in y.zs", :key="z.id") 123
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 5,
          column: 27,
          endLine: 5,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="x in xs")
  template(v-for="y in x.ys")
    li(v-for="z in a.zs", :key="z.id") 123
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 5,
          column: 27,
          endLine: 5,
          endColumn: 38
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `
        <template lang="pug">
template(v-for="x in xs")
  template(v-for="y in x.ys")
    li(v-for="z in x.zs", :key="z.id") 123
</template>`,
      errors: [
        {
          message:
            "Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive.",
          line: 5,
          column: 27,
          endLine: 5,
          endColumn: 38
        }
      ]
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">div(v-for=)</template>`,
      errors: [
        {
          message: "'v-for' directives require that attribute value.",
          line: 1,
          column: 16,
          endLine: 1,
          endColumn: 24
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div
  div(v-for="(,a) in list")
</template>`,
      options: [{ allowEmptyAlias: false }],
      errors: [
        {
          message: 'Invalid empty alias.',
          line: 3,
          column: 14,
          endLine: 3,
          endColumn: 26
        }
      ]
    }
  ]
})
