// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/3868a2d6e7b44037dd5aa04a7acdd857a0358a7b/tests/lib/rules/valid-v-show.test.ts
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
import { RuleTester } from '../../../eslint-compat'
import rule from 'eslint-plugin-vue/dist/rules/valid-v-show'
import vueEslintParser from 'vue-eslint-parser'

const tester = new RuleTester({
  languageOptions: {
    parser: vueEslintParser,
    ecmaVersion: 2015,
    parserOptions: {
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    }
  }
})

tester.run('valid-v-show', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-show="foo")</template>`
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">MyComponent(v-show=".")</template>`
    },
    // comment value (parsing error)
    {
      filename: 'comment-value.vue',
      code: `<template lang="pug">MyComponent(v-show="/**/")</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-show:aaa="foo")</template>`,
      errors: [
        {
          message: "'v-show' directives require no argument.",
          line: 1,
          column: 33,
          endLine: 1,
          endColumn: 36
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-show.aaa="foo")</template>`,
      errors: [
        {
          message: "'v-show' directives require no modifier.",
          line: 1,
          column: 33,
          endLine: 1,
          endColumn: 36
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-show)</template>`,
      errors: [
        {
          message: "'v-show' directives require that attribute value.",
          line: 1,
          column: 26,
          endLine: 1,
          endColumn: 32
        }
      ]
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">div(v-show="")</template>`,
      errors: [
        {
          message: "'v-show' directives require that attribute value.",
          line: 1,
          column: 26,
          endLine: 1,
          endColumn: 35
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">template(v-show="condition")</template>`,
      errors: [
        {
          message: "'v-show' directives cannot be put on <template> tags.",
          line: 1,
          column: 31,
          endLine: 1,
          endColumn: 49
        }
      ]
    }
  ]
})
